### ISSUE TITLE
Two-way clustered standard errors incorrect?

### ISSUE THREAD

**Issue by tatyanaderyugina** [sergiocorreia/reghdfe#101]
When doing two-way clustering, reghdfe reports the number of clusters incorrectly, and standard errors barely change relative to one-way clustering. The latter is surprising in our case and makes me think that multi-way clustering is not working correctly.

See example below (this ran on a 0.01% random subsample of our data). Number of unique_id clusters is 7,472 (this is our panel id variable); number of bill_year#bill_month clusters is 78 (this is our time variable). When two-way clustering by unique_id and bill_year#bill_month, reghdfe reports only 78 clusters, which is incorrect. The reported standard errors are also nearly identical to those reported when clustering by bill_year#bill_month only. Could you check the multi-way clustering feature?

**TWO WAY CLUSTERING**
reghdfe log_total_sqft diffCDD diffHDD diffCDDxpost diffHDDxpost, absorb(i.year_built i.zip i.border#i.bill_year#i.bill_month) vce(cluster  i.bill_year#i.bill_month unique)
(dropped 131 singleton observations)
(converged in 34 iterations)

HDFE Linear regression                            Number of obs   =      7,510
Absorbing 3 HDFE groups                           F(   4,     77) =       1.95
Statistics robust to heteroskedasticity           Prob > F        =     0.1107
                                                  R-squared       =     0.4316
                                                  Adj R-squared   =     0.3429
Number of clusters (bill_year#bill_month) =         78Within R-sq.=     0.0013
Number of clusters (unique_id) =      7,472       Root MSE        =     0.4919

        (Std. Err. adjusted for 78 clusters in bill_year#bill_month unique_id)
------------------------------------------------------------------------------
             |               Robust
log_total_~t |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
     diffCDD |   -.003473    .001843    -1.88   0.063    -.0071429    .0001968
     diffHDD |   .0015544   .0027494     0.57   0.573    -.0039205    .0070292
diffCDDxpost |  -.0024631   .0020794    -1.18   0.240    -.0066038    .0016776
diffHDDxpost |  -.0032778   .0023944    -1.37   0.175    -.0080456      .00149
------------------------------------------------------------------------------

Absorbed degrees of freedom:
------------------------------------------------------------------------------+
                Absorbed FE |  Num. Coefs.  =   Categories  -   Redundant     | 
----------------------------+-------------------------------------------------|
                 year_built |           57              57              0     | 
                        zip |          237             238              1     | 
border#bill_year#bill_month |            0             717            717 *   | 
------------------------------------------------------------------------------+
* = fixed effect nested within cluster; treated as redundant for DoF computation

**ONE WAY CLUSTERING BY UNIQUE_ID**
reghdfe log_total_sqft diffCDD diffHDD diffCDDxpost diffHDDxpost, absorb(i.year_built i.zip i.border#i.bill_year#i.bill_month) vce(cluster  unique)
(dropped 131 singleton observations)
(converged in 34 iterations)

HDFE Linear regression                            Number of obs   =      7,510
Absorbing 3 HDFE groups                           F(   4,   7471) =       1.89
Statistics robust to heteroskedasticity           Prob > F        =     0.1087
                                                  R-squared       =     0.4316
                                                  Adj R-squared   =     0.3435
                                                  Within R-sq.    =     0.0013
Number of clusters (unique_id) =      7,472       Root MSE        =     0.4916

                          (Std. Err. adjusted for 7,472 clusters in unique_id)
------------------------------------------------------------------------------
             |               Robust
log_total_~t |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
     diffCDD |   -.003473   .0021635    -1.61   0.108    -.0077141    .0007681
     diffHDD |   .0015544   .0024635     0.63   0.528    -.0032748    .0063836
diffCDDxpost |  -.0024631   .0021673    -1.14   0.256    -.0067116    .0017854
diffHDDxpost |  -.0032778   .0020719    -1.58   0.114    -.0073393    .0007837
------------------------------------------------------------------------------

Absorbed degrees of freedom:
------------------------------------------------------------------------------+
                Absorbed FE |  Num. Coefs.  =   Categories  -   Redundant     | 
----------------------------+-------------------------------------------------|
                 year_built |           57              57              0     | 
                        zip |          237             238              1     | 
border#bill_year#bill_month |          711             717              6 ?   | 
------------------------------------------------------------------------------+
? = number of redundant parameters may be higher

**ONE WAY CLUSTERING BY i.bill_year#i.bill_month**
. reghdfe log_total_sqft diffCDD diffHDD diffCDDxpost diffHDDxpost, absorb(i.year_built i.zip i.border#i.bill_year#i.bill_month) vce(cluster  i.bill_year#i.bill_month)
(dropped 131 singleton observations)
(converged in 34 iterations)

HDFE Linear regression                            Number of obs   =      7,510
Absorbing 3 HDFE groups                           F(   4,     77) =       1.95
Statistics robust to heteroskedasticity           Prob > F        =     0.1105
                                                  R-squared       =     0.4316
                                                  Adj R-squared   =     0.3429
                                                  Within R-sq.    =     0.0013
Number of clusters (bill_year#bill_month) =         78Root MSE    =     0.4919

                  (Std. Err. adjusted for 78 clusters in bill_year#bill_month)
------------------------------------------------------------------------------
             |               Robust
log_total_~t |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
     diffCDD |   -.003473    .001842    -1.89   0.063    -.0071409    .0001948
     diffHDD |   .0015544   .0027485     0.57   0.573    -.0039185    .0070273
diffCDDxpost |  -.0024631   .0020787    -1.18   0.240    -.0066023    .0016761
diffHDDxpost |  -.0032778   .0023937    -1.37   0.175    -.0080442    .0014886
------------------------------------------------------------------------------

Absorbed degrees of freedom:
------------------------------------------------------------------------------+
                Absorbed FE |  Num. Coefs.  =   Categories  -   Redundant     | 
----------------------------+-------------------------------------------------|
                 year_built |           57              57              0     | 
                        zip |          237             238              1     | 
border#bill_year#bill_month |            0             717            717 *   | 
------------------------------------------------------------------------------+
* = fixed effect nested within cluster; treated as redundant for DoF computation

**Comment by sergiocorreia** [comment]
For two-way-clustering, `reghdfe` follows common practice and sets the number of clusters to be the smallest number of clusters across the two dimensions (I think that's what `ivreg2` does, as well as what Cameron et al suggest).

You can see the line that does this [here](https://github.com/sergiocorreia/reghdfe/blob/master/src/reghdfe_common.mata#L462)

Thus, in your case, N_clust = min(78, 7472) = 78
