### ISSUE TITLE
reghdfe not selecting omitted category correctly

### ISSUE THREAD

**Issue by tatyanaderyugina** [sergiocorreia/reghdfe#102]
When including interactions in reghdfe, it seems to omit too many categories. For example, if you include the interaction x1#x2, it omits an entire value of x1 rather than one combination of x1 and x2. While this can be remedied by also including x1 and x2 on their own, it does not correspond to how Stata treats variable interactions and, in my opinion, should be changed. Sample code to reproduce the issue followed by the output of reghdfe versus Stata is below.

clear all
set obs 10000

gen x1=runiformint(1,3)
gen x2=runiformint(1,3)
gen x3=runiformint(1,10)

gen y=rnormal()

reghdfe y i.x1#i.x2, absorb(x3) vce(robust)
areg y i.x1#i.x2, absorb(x3) vce(robust)

OUTPUT:

reghdfe y i.x1#i.x2, absorb(x3) vce(robust)
(converged in 1 iterations)

HDFE Linear regression                            Number of obs   =     10,000
Absorbing 1 HDFE group                            F(   4,   9986) =       0.82
Statistics robust to heteroskedasticity           Prob > F        =     0.5103
                                                  R-squared       =     0.0010
                                                  Adj R-squared   =    -0.0003
                                                  Within R-sq.    =     0.0003
                                                  Root MSE        =     0.9998

------------------------------------------------------------------------------
             |               Robust
           y |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       x1#x2 |
        2 2  |   .0013843   .0329946     0.04   0.967    -.0632918    .0660604
        2 3  |   .0293464   .0345614     0.85   0.396    -.0384009    .0970937
        3 2  |   .0373976   .0319404     1.17   0.242    -.0252121    .1000073
        3 3  |   .0456798   .0323761     1.41   0.158    -.0177838    .1091434
------------------------------------------------------------------------------

Absorbed degrees of freedom:
---------------------------------------------------------------+
 Absorbed FE |  Num. Coefs.  =   Categories  -   Redundant     | 
-------------+-------------------------------------------------|
          x3 |           10              10              0     | 
---------------------------------------------------------------+

areg y i.x1#i.x2, absorb(x3) vce(robust)

Linear regression, absorbing indicators         Number of obs     =     10,000
                                                F(   8,   9982)   =       0.53
                                                Prob > F          =     0.8375
                                                R-squared         =     0.0011
                                                Adj R-squared     =    -0.0006
                                                Root MSE          =     1.0000

------------------------------------------------------------------------------
             |               Robust
           y |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       x1#x2 |
        1 2  |  -.0106588   .0417771    -0.26   0.799    -.0925503    .0712327
        1 3  |   .0122509   .0424544     0.29   0.773    -.0709684    .0954701
        2 1  |  -.0208906   .0421452    -0.50   0.620    -.1035038    .0617225
        2 2  |  -.0002058   .0421923    -0.00   0.996    -.0829112    .0824996
        2 3  |   .0277682   .0434404     0.64   0.523    -.0573838    .1129203
        3 1  |   .0101257   .0419626     0.24   0.809    -.0721295    .0923809
        3 2  |   .0358086   .0414056     0.86   0.387    -.0453547     .116972
        3 3  |   .0441032   .0417248     1.06   0.291    -.0376859    .1258922
             |
       _cons |  -.0132449   .0295181    -0.45   0.654    -.0711064    .0446166
-------------+----------------------------------------------------------------
          x3 |   absorbed                                      (10 categories)

**Comment by sergiocorreia** [comment]
What version of reghdfe are you using? You can find out with `which reghdfe` or `reghdfe, version`.

The latest version is `4.3.6 28jun2017` and fixes most of the interaction issues..

**Comment by tatyanaderyugina** [comment]
I was using one from 2016 (the one that's up on SSC). I'll update!

**Comment by dmitrykhm** [comment]
Same issue here. After updating for the latest version (4.3.6 28jun2017) Stata 12 gives an error: 
fixed_effects():  3499  _selectindex() not found
reghdfe, version says ftools and boottest are in place.

Replicating reghdfe with hdfe as in the [example](http://scorreia.com/demo/hdfe.html) here gives correct results, though.

**Comment by sergiocorreia** [comment]
For Stata 12, you also need the boottest package (which provides replacements for the selectindex() function added on Stata 13).

**Comment by dmitrykhm** [comment]
Yes, I have the latest boottest installed. I'm trying to reinstall it, but it looks like my connection is down. 
Anyway, this could be the reason (from boottest version history):
* 1.5.7 renamed _selectindex() to boottest_selectindex() to reduce conflicts with old cmp versions

**Comment by sergiocorreia** [comment]
I just [updated](https://github.com/sergiocorreia/ftools/commit/5a6bc4880e0a0457e5056bf53e19bc59e37848b9#diff-8b4248439a182d11ee72b43a90abb218) `ftools` so it uses `boottest_selectindex`.

Note that you need to reinstall ftools for that (which you can do quickly by typing `reghdfe, update`).

**Comment by dmitrykhm** [comment]
Thank you for a quick reply, Sergio!
I've updated the `ftools` installation but keep receiving the same error: I reinstalled everything (`ftools`, `reghdfe`, `boottest`), so I've got this:
```
. reghdfe, version
~/Library/Application Support/Stata/ado/stbplus/r/reghdfe.ado
*! version 4.3.6 28jun2017

Required packages installed?
- ftools            yes
- boottest          yes

. which boottest
~/Library/Application Support/Stata/ado/stbplus/b/boottest.ado
*! boottest 1.5.7 19 June 2017
*! Copyright (C) 2015-17 David Roodman

. which ftools
~/Library/Application Support/Stata/ado/stbplus/f/ftools.ado
*! version 2.13.5 09jul2017
```
And the error is still there:
```
. sysuse citytemp, clear
(City Temperature Data)

. reghdfe tempjuly tempjan, a(region)
         fixed_effects():  3499  _selectindex() not found
                 <istmt>:     -  function returned error
```
Here's the trace:
```
    - mata: HDFE = fixed_effects(`"`absorb' `comma' `options'"', "`touse'", "`weight'", "`exp'", `drop_singletons', `verbose')
    = mata: HDFE = fixed_effects(`"region , "', "__000001", "", "", 1, 0)
         fixed_effects():  3499  _selectindex() not found
                 <istmt>:     -  function returned error
    ------------------------------------------------------------------------------------------------------------------ end reghdfe.Parse ---
```

**Comment by sergiocorreia** [comment]
It seems reghdfe is still looking for the old selectindex.

Can you try running "reghdfe, compile" and "ftools, compile", followed by "program drop _all"?

**Comment by dmitrykhm** [comment]
That solved it perfectly! Thanks!
I guess, you have this magic in `reghdfe, update`, but I couldn't run it: (my?) Stata 12 can't get anything via `https`, so I had to reinstall everything manually. Compilation did the trick.
Thanks for a great package!

**Comment by sergiocorreia** [comment]
Oh, you are right; I forgot about https.

Great to hear it works now, cheers!
