### ISSUE TITLE
Baselevel for Factor Variable not Displayed Properly

### ISSUE THREAD

**Issue by zqian1** [sergiocorreia/reghdfe#103]
Hi Sergio, 

I am using the current stable version of reghdfe. It seems when I use the baselevel option, the baselevel for factor variable is still not displayed. I need the baselevel coefficient when I plot the coefficients. Thanks for your help! 

	use "http://dss.princeton.edu/training/Panel101.dta", clear
	gen time = (year>=1994) & !missing(year)
	gen treated = (country>4) & !missing(country)
	gen did = time*treated

        areg y i.treated did, a(time) allbaselevels

	Linear regression, absorbing indicators         Number of obs     =         70
	                                                F(   2,     66)   =       1.57
	                                                Prob > F          =     0.2164
	                                                R-squared         =     0.0827
	                                                Adj R-squared     =     0.0410
	                                                Root MSE          =  2.953e+09

	------------------------------------------------------------------------------
	           y |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
	-------------+----------------------------------------------------------------
	     treated |
	          0  |          0  (base)
	          1  |   1.78e+09   1.13e+09     1.58   0.120    -4.75e+08    4.03e+09
	             |
	         did |  -2.52e+09   1.46e+09    -1.73   0.088    -5.43e+09    3.87e+08
	       _cons |   1.73e+09   4.67e+08     3.71   0.000     8.00e+08    2.66e+09
	-------------+----------------------------------------------------------------
	        time |          F(1, 66) =      5.772   0.019           (2 categories)

	reghdfe y i.treated did, a(time) allbaselevels

	HDFE Linear regression                            Number of obs   =         70
	Absorbing 1 HDFE group                            F(   2,     66) =       1.57
	                                                  Prob > F        =     0.2164
	                                                  R-squared       =     0.0827
	                                                  Adj R-squared   =     0.0410
	                                                  Within R-sq.    =     0.0453
	                                                  Root MSE        =  2.953e+09

	------------------------------------------------------------------------------
	           y |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
	-------------+----------------------------------------------------------------
	     treated |
	          1  |   1.78e+09   1.13e+09     1.58   0.120    -4.75e+08    4.03e+09
	             |
	         did |  -2.52e+09   1.46e+09    -1.73   0.088    -5.43e+09    3.87e+08
	-------------+----------------------------------------------------------------
	    Absorbed |          F(1, 66) =      5.772   0.005             (Joint test)
	------------------------------------------------------------------------------

	Absorbed degrees of freedom:
	---------------------------------------------------------------+
	 Absorbed FE |  Num. Coefs.  =   Categories  -   Redundant     | 
	-------------+-------------------------------------------------|
	        time |            2               2              0     | 
	---------------------------------------------------------------+

**Comment by sergiocorreia** [comment]
Can you try the latest version? It should have fixed that issue

**Comment by zqian1** [comment]
I tried installing the development version following the instruction [here](http://scorreia.com/software/reghdfe/install.html), but the problem persists. I am running Stata 14.1 on Ubuntu.

**Comment by sergiocorreia** [comment]
I can see that. I dug into the code and finding a fix to that seems quite cumbersome because of the way reghdfe interacts with Stata/Mata. A solution would involve keeping track of the base variables and then expanding the resulting e(b) and e(V) matrices to put those base variables back in the correct positions (which might change depending on the number of factors created, variables dropped, etc.).

So, all in all, I don't see a fix for that on the short term

**Comment by zqian1** [comment]
I will give that a try. Thanks for your help! Feel free to close the issue.

**Comment by ryanedmundkessler** [comment]
Sad to hear there's no easy fix here! I ran into the same issue today (Hi @zqian1!)

**Comment by sergiocorreia** [comment]
I had the same problem as @zqian when using coefplot, and luckily found a way to change the code without many complications.

Thus, the latest commit (1905f1b) *should* fix this issue:

```
. reghdfe, version
c:\ado\plus\r\reghdfe.ado
*! version 4.5.0 07jun2018

Required packages installed?
- ftools            yes

. ftools, version
c:\ado\plus\f\ftools.ado
*! version 2.28.0 07jun2018

Required packages installed?
- moremata          yes

. 
. sysuse auto
(1978 Automobile Data)

. reghdfe price i.foreign, noabsorb base
(MWFE estimator converged in 1 iterations)

HDFE Linear regression                            Number of obs   =         74
Absorbing 1 HDFE group                            F(   1,     72) =       0.17
                                                  Prob > F        =     0.6802
                                                  R-squared       =     0.0024
                                                  Adj R-squared   =    -0.0115
                                                  Within R-sq.    =     0.0024
                                                  Root MSE        =  2966.3811

------------------------------------------------------------------------------
       price |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
     foreign |
   Domestic  |          0  (base)
    Foreign  |   312.2587   754.4488     0.41   0.680    -1191.708    1816.225
------------------------------------------------------------------------------

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
       _cons |         1           0           1     |
-----------------------------------------------------+
```

This also requires an update in ftools, and might benefit from more eyeballs (I only checked that the new version passed the existing tests, so there might be corner cases where this doesn't work perfectly)

**Comment by zqian1** [comment]
@sergiocorreia: I ended up writing a function of my own to modify the e(b) and e(V) matrices. Thanks a lot for the fix! Very helpful! 

@ryanedmundkessler: Nice to run into you here :)
