### ISSUE TITLE
ranktest not installed: To install, from within Stata type r(601);

### ISSUE THREAD

**Issue by Danferno** [sergiocorreia/reghdfe#105]
```
Error: must have ranktest version 01.3.02 or greater installed
To install, from within Stata type r(601);
```

I assume r(601) should be, "ssc install ranktest"?

Stata 14.2, 
*! reghdfe 3.2.9 21feb2016

**Comment by sergiocorreia** [comment]
Can you try with reghdfe 4, on GitHub?

**Comment by Danferno** [comment]
```
. reghdfe D_$depvar ${DLx_$indepvar} $D_controls (DL1_$depvar = L2.$depvar), absorb($timevar) residuals(res_`name')
(MWFE estimator converged in 1 iterations)
            assert_msg():  3498  You can only run OLS with reghdfe; for IV see https://github.com/sergiocorreia/ivreg2_demo
                 <istmt>:     -  function returned error
```

Has this changed since previous versions?

*! version 4.3.6 28jun2017

**Comment by sergiocorreia** [comment]
Yep. I decoupled IV from reghdfe, as it was making the code a mess (basically, having to trick ivreg2 was a convoluted piece of code, 100s of lines long).

Now, I just modify ivreg2 and add an absorb() option to it, which calls reghdfe.

Do.note that the 3.x version of reghdfe is available with the "old" option

**Comment by Danferno** [comment]
Ah, makes sense. Thanks!
