### ISSUE TITLE
IV Regression hangs with medium-sized dataset

### ISSUE THREAD

**Issue by jimmyg909** [sergiocorreia/reghdfe#108]
Hi!

I am using -reghdfe- because I am clustering my SEs in two dimensions and -reghdfe- is known to provide SEs that use the correct DOF correction from Cameron, Gelbach, Miller (2011). For this reason I prefer -reghdfe- to -felm- in R because it does not perform the correct DOF correction for two-way clustering. I've verified the differences in my estimates and while they are small, I am having trouble replicating the R estimates by calculating the DOF adjustment myself. Thus, I would prefer to use -reghdfe- for my estimates so I can be confident the SEs account for the right asymptotic DOF correction. 

In my main specifications I am estimating an IV regression with a single endogenous variable and single instrument and many FEs. The issue is -reghdfe- never converges when I give it a model with more than a few hundred thousand observations.

The command I am running is of the form
reghdfe Y control1 control2 (D = Z), absorb(iFE tFE) vce(cluster iFE tFExGEO)

where D is my endogenous regressor and Z is the instrument. I include 2 controls and individual (iFE) and time-of-sample (tFE) fixed effects. I cluster my standard errors by individual and time-of-sample by geographic region (tFExGEO) - think ZIP codes. I ran the following two regressions on two datasets where the first is a shorter panel than the second. Here are the basic stats for each:

Run #1 (completes in 15 seconds)
N = 119,863
iFE clusters = 2,411
tFExGEO = 1,812

Run #2 (stalls for 30+ minutes until I click "break" and then I get the output pasted below)
N = 288,091
iFE clusters = 2,411
tFExGEO = 53,533
![example](https://user-images.githubusercontent.com/11397958/29102264-bc8d99cc-7c6c-11e7-91a4-3df3d155f0d7.PNG)

I know -reghdfe- ports the IV estimation to -ivreg2- so perhaps this is an issue with that command, but I figured there may be some issue with the way the -reghdfe- algorithm interacts with the IV estimation, resulting in the command getting stuck trying to invert a very big matrix. As a benchmark -felm- in R provides a response in <1 min with Run #2 above. I am trying to reconcile the two so I can decide how to best proceed.

It is also worth noting that I have used -reghdfe- to estimate the reduced form of the model with 10,000,000+ observations and more FEs than in Run #2 so I am confident -reghdfe- can handle the dataset with OLS. 

I also want to say thanks for developing this command. It is very helpful and I really appreciate it!

Thanks,
Jimmy

**Comment by sergiocorreia** [comment]
Hi Jimmy, 

Yes, I suspect you are right and the issue might be a corner case with the  rankest command.

Three quick  things (on mobile):

1. Can you type "set trace on" and rerun it, to see exactly where does it stall? (The verbose option of reghdfe also helps there)
2. Can you try with the new version of reghdfe? Not only it's 3x as fast, but might deal with this better . The IV version is here: https://github.com/sergiocorreia/ivreg2_demo/ (note that it also requires ftools, which helps to deal with large datasets)
3. If all else happens, it might be useful to have a sample dataset where I can reproduce the issue.

**Comment by jimmyg909** [comment]
Thanks for the quick reply Sergio. Here are some responses:

I ran with set trace on with my version of -reghdfe- (installed via ssc) and after installing 4.x. Here are both results, they appear to be stalling at the same point:

old version
![trace_hang](https://user-images.githubusercontent.com/11397958/29103154-b8f49d46-7c72-11e7-9b52-d52d2847105c.PNG)

new version
![trace_hang_v4](https://user-images.githubusercontent.com/11397958/29103158-c3040308-7c72-11e7-81d9-b9354643998f.PNG)

I also re-ran Run #1 successfully from my initial post with the -ivreghdfe- command to verify that I had the syntax correct. The command I am running is:
ivreghdfe logkwh CDH HDH (ENRLxEVHRxCALL = ENRL), a(iFExHoD tFE) cluster(iFE tFExCZxIOU)

As for #3, I can try to synthesize data, but I am working with confidential PII so I cannot upload the dataset as is. If the problem is not clear from the above process, I will see what I can do to anonymize the PII for replication.

**Comment by sergiocorreia** [comment]
The Omega mata function is part of ivreg2, so I would have to ping it's authors to see what's going on.

About anonymizing the data, I suspect the problem might be due to the structure of the FEs and not the y/x variables per se, so it should be feasible.

**Comment by sergiocorreia** [comment]
Can you try running the command with the `noid` option (which tells `ivreg` to avoid computing the underidentification stats). It would help to pinpoint the issue.

**Comment by jimmyg909** [comment]
I ran the -ivreghdfe- command with the -noid- option. Run 1 was successful, but the command did not run successfully for Run 2.  Here is the output:

without -set trace on-
![run_w_noid_notrace](https://user-images.githubusercontent.com/11397958/29145650-da88c874-7d12-11e7-86db-03a4897f0937.PNG)

with -set trace on-
![run_w_noid_trace](https://user-images.githubusercontent.com/11397958/29145657-decbc440-7d12-11e7-924c-47d776748972.PNG)

**Comment by sergiocorreia** [comment]
That's a quite unusual mistake. That assertion is part of the core of reghdfe, which gets run *before* the omega code. This means that the command should also fail with the new version of reghdfe and not just when running IV (for the same variables, as there might be some with MVs)

The culprit is in [line 429](https://github.com/sergiocorreia/reghdfe/blob/master/src/reghdfe_class.mata#L429) which gets called when some of your regressors are perfectly collinear. So at least we know that you have variables that should be omitted.

I'm not sure what corner case could create this issue, so can you try i) dropping regressors one by one, and ii) creating a random regressor (`gen x = runiform()`) and then adding that to the list of regressors?

**Comment by sergiocorreia** [comment]
Also, what version of Stata do you have?

**Comment by jimmyg909** [comment]
I am using 4-core STATA 15 MP on Linux. I have been working to generate a synthetic dataset for you that replicates the issue, but the program was working for the Run 2 sized dataset (I was not immediably able to replicate the error from the first post or earlier). I added more observations to the panel and the hanging has occurred again at the omega code. I've sent you a synthetic dataset that has hangs at the same place.

**Comment by sergiocorreia** [comment]
Mark Schaffer (one of the authors of `ivreg2`) was thinking you might be running the newest Stata, so that might related.

Can you try running it with version control, i.e. running

```stata
version 14: ivreghdfe ...
```
