### ISSUE TITLE
After update: select():  3200  conformability error

### ISSUE THREAD

**Issue by heidenfahrt** [sergiocorreia/reghdfe#111]
After updating today to the most recent version via `adoupdate, update`, an estimation with many absorbed effects yields the following error:
```
                select():  3200  conformability error
  Factor::__inner_drop():     -  function returned error
Factor::drop_singletons():     -  function returned error
         fixed_effects():     -  function returned error
                 <istmt>:     -  function returned error
```
With `reghdfe, old` it still works.

**Comment by sergiocorreia** [comment]
Oh, I can see why.

You need to update `ftools` to the latest version (and perhaps also run `ftools, compile`.

**Comment by heidenfahrt** [comment]
Indeed, that was all. Thank you.

**Comment by sergiocorreia** [comment]
Michael,

What version of `ftools` are you using?

**Comment by michael-evers** [comment]
It's the `ftools` package from http://fmwww.bc.edu/repec/bocode/f/

I believe it's from July 2017.  I'm also running Stata 13.1 so have had to install from the packages from their zip files.

**Comment by sergiocorreia** [comment]
I'm pretty sure that if you update ftools from the latest (github) version, it will work.

**Comment by michael-evers** [comment]
Updated to `ftools` March 2018 version.  That fixed it.

Thanks

**Comment by michelenepo** [comment]
Hi, I'm having the same problem, I tried all the options given above and it's still giving the same error. 
                              *:  3200  conformability error
            _xsmle_est():     -  function returned error
                 <istmt>:     -  function returned error
