### ISSUE TITLE
Bug or Metrics: IV standard errors smaller than OLS

### ISSUE THREAD

**Issue by felixholub** [sergiocorreia/reghdfe#112]
[Cross-Post from [https://www.statalist.org/forums/forum/general-stata-discussion/general/1409541-standard-errors-lower-in-iv-than-ols-ivreghdfe-and-reghdfe](https://www.statalist.org/forums/forum/general-stata-discussion/general/1409541-standard-errors-lower-in-iv-than-ols-ivreghdfe-and-reghdfe) ]

I'm running an estimation where `reghdfe` produces a higher standard error for OLS than 2SLS, using `ivreghdfe` or `reghdfe, old`. When I do not cluster standard errors, then the ranking changes. 

As far as I remember, OLS standard errors should always be smaller than 2SLS standard errors. But besides some discussions like https://stats.stackexchange.com/questions/242762/why-is-the-variance-of-2sls-bigger-than-that-of-ols?rq=1 I actually cannot find credible sources on that .

Hence, are the calculated errors correct and I'm just missing something in the metrics of clustered standard errors, or is that a bug?

**Comment by sergiocorreia** [comment]
If the dimension you are clustering on is the same dimension as the instrument (e.g. your instrument is at the country level and you have country fixed effects) then I would expect 2SLS standard errors to be quote close to OLS ones. 

Also, clustered standard errors are usually larger than unclustered ones, but can be smaller with negative correlation within cluster (see [page 13](http://repec.org/usug2007/crse.pdf)).

So, as far as I know, there is no rule, but your results don't really surprise me.

**Comment by felixholub** [comment]
That makes sense, thanks a lot Sergio. I owe you several drinks;) Good to hear that the program is running just fine.
