### ISSUE TITLE
Plotting ommited variable with coefplot

### ISSUE THREAD

**Issue by RichMurphy** [sergiocorreia/reghdfe#114]
Hi, 
Thanks for the great command. 
I'm running a specification with many fixed effects which I'm absorbing. There is also a categorical variable that I want to see the coefs of and omit a specific category.  
So I run : _reghdfe outcome ib10.categoryvar ,absorb(fe)_  
Then I want to plot the coef of the categorical variable.
So I run:  _coefplot, omitted baselevel_ 
The issue I have is that it's not plotting the omitted category. 

Running: _reg outcome ib10.categoryvar_  or _areg outcome ib10.categoryvar ,absorb(fe)_  - with the same coefplot command plots the ommited category.

Any advice?
Best regards ,
Rich

**Comment by felixholub** [comment]
Hey Rich, 
Why don't you use the possibility to store fixed effects added to absorb? You can just absorb(newname= yourvariable), so the values are stored in a new variable, newname. Then it's easy to plot etc.
Probably Sergio will point out that these FE are not estimated consistently though. 

⁣Gesendet mit TypeApp ​

**Comment by RichMurphy** [comment]
Hey Felix, 
That's a possibility, if I understand what you meant: _reghdfe outcome ,absorb(fe categoryvar)_ 
The problem with that is I can't specify which is the omitted category. I specifically want to have the middle category as the omitted one (to have better standard errors on the remaining categories). 
Unless there is a way that I don't know about. 

Cheers
Rich

**Comment by sergiocorreia** [comment]
Felix's comment is one possibility, specially if you have many categories.

But still, you will realize that these estimates have mean zero, which is just a different normalization that the one you get when you include the fixed effects as dummies, in which case we just drop one dummy (i.e. force its coef to be zero).

To fix this, one way or the other, you would have to look into the internals of coefplot. For instance, I see that it allows a -matrix- option. Maybe you can compute the constant [by hand](http://scorreia.com/software/reghdfe/faq.html#where-is-the-constant) and then add construct a matrix `b = e(b) + constant` which you can then pass to coefplot?

**Comment by RichMurphy** [comment]
Thanks Sergio, 
Yeah, it's no mystery what the value of the omitted category is going to be, and I could adjust all the coefs accordingly. 
The issue is that i'm in a particular situation where my categorical variable only has 10 values and there is very little common support in the first category. So want to exclude the middle one to obtain sensible standard errors for the majority of categories. Like i said, i can get the results through areg, and so may just use that instead. I prefer your command because it is much faster with my data (6m obs, 20k fe). 
Cheers
Rich

**Comment by sergiocorreia** [comment]
Yeah, the problem is a bit tricky to solve because reghdfe actually drops the base variables from e(b), while areg keeps them as zero.  We drop them to speed computations (e.g. no point in trying to demean a vector of zeros), but we could add them back after the computations are done. That would be tricky thought, so it will have to wait a bit..

**Comment by RichMurphy** [comment]
Good to know I wasn't missing anything obvious. 
Thanks again for this command. 
R
