### ISSUE TITLE
Number of singletons in stored results

### ISSUE THREAD

**Issue by olidess** [sergiocorreia/reghdfe#116]
Hi Sergio,

I have a stupid question. Is there a way to tabulate the number of singletons dropped by reghdfe with esttout? Basically, I would like to report the total number of observations, both with and without singletons. Is there anyway to do that? In the stored results, can we have something like e(N_singletons)?

Thank you so much for your help!!!

Best,

OD

**Comment by sergiocorreia** [comment]
Yes. It's called e(num_singletons); there's a lot of stuff in the e(..) results, which you can check with ereturn list.

An example below (of how I usually do it):

```
sysuse auto

* Run and store regressions
reghdfe price weight length, a(turn)
estadd scalar N_true = e(N) + e(num_singletons)
estimates store model1
reghdfe price weight length, a(turn trunk)
estadd scalar N_true = e(N) + e(num_singletons)
estimates store model2
reghdfe price weight gear length, a(turn foreign)
estadd scalar N_true = e(N) + e(num_singletons)
estimates store model3

* Create table
estfe model*, labels(turn "Turn FE" turn#trunk "Turn-Trunk FE")
esttab model* , indicate("Length Controls=length" `r(indicate_fe)', labels("Yes" "-")) stats(N num_singletons N_true, labels("Obs." "Singletons" "True obs."))
```

**Comment by olidess** [comment]
Fantastic! Thank you so much Sergio !!!

**Comment by olidess** [comment]
Hi Sergio,

Sorry to come back on this, but I do not have e(num_singletons) in ereturn list. Here is what I have. How can I get  e(num_singletons)?

Thank you so much for your help!

Best,

Olivier

[cid:image003.png@01D3548A.DB0BF3D0]

**Comment by sergiocorreia** [comment]
My guess is you are using reghdfe 3 from SSC instead of 4, from GitHub. You can check with the -which- command.

**Comment by olidess** [comment]
Yes,

That's indeed the version 3 that I was using. I am now using version 4.4.11, and the number of singletons is indeed available in ereturn list.

I have seen that the new version does not handle IV anymore. I have downloaded IVREGHDFE from GitHub. Is that the correct new command for IV with FEs?

Thank you so much for your help

Best,

Olivier

________________________________

**Comment by sergiocorreia** [comment]
Yes. I moved the IV code out of reghdfe b/c things were getting too complex. 

Ivreghdfe is just ivreg2 with a few extra lines that do the demeaning in the background.

**Comment by olidess** [comment]
Hi Sergio,

I hope this email finds you well. Sorry to bother you! I tried to install the last version of your reghdfe command from your website, using  exactly your code, and I got the following message error. Do you have any idea of how I could fix that? I tried to look for an easy fix on the web, and could not find any clear solution.

Thank you so much for your help!!

 net install moresyntax, from("https://github.com/sergiocorreia/moresyntax/raw/master/src/")
Received fatal alert: protocol_version
https://github.com/sergiocorreia/moresyntax/raw/master/src/ either
  1)  is not a valid URL, or
  2)  could not be contacted, or
  3)  is not a Stata download site (has no stata.toc file).

current site is still http://fmwww.bc.edu/repec/bocode/r/
r(5100); t=1.69 19:18:51

. ado uninstall moresyntax
package not found
r(111); t=0.00 19:19:05

________________________________

**Comment by sergiocorreia** [comment]
Yep, sorry, the website is not updated (moresyntax is now part of ftools). A better set of instructions is in the ivreghdfe repo: https://github.com/sergiocorreia/ivreghdfe#installation-steps

```
* Install ftools (remove program if it existed previously)
cap ado uninstall moresyntax
cap ado uninstall ftools
net install ftools, from("https://github.com/sergiocorreia/ftools/raw/master/src/")

* Install reghdfe 4.x
cap ado uninstall reghdfe
net install reghdfe, from("https://github.com/sergiocorreia/reghdfe/raw/master/src/")

* Install boottest for Stata 11 and 12
if (c(version)<13) cap ado uninstall boottest
if (c(version)<13) ssc install boottest

* Install moremata (sometimes used by ftools but not needed for reghdfe)
cap ssc install moremata

* Install ivreg2, the core package
ssc install ivreg2

* Finally, install this package
cap ado uninstall ivreg2hdfe
cap ado uninstall ivreghdfe
net install ivreghdfe, from(https://github.com/sergiocorreia/ivreg2_demo/raw/master/)
```

**Comment by olidess** [comment]
Yes Sergio,

I tried your new code, and I ran into the same issue of “fatal alert”

[cid:image003.png@01D3F340.37FA1870]

**Comment by sergiocorreia** [comment]
Are you using Stata 13 or older, or behind a proxy or server without https access?

**Comment by sergiocorreia** [comment]
I see. Only Stata 14+ supports internet access through https, which is now the *only* method GitHub supports.on the earlier link I provided, there are some instructions, but the short version is that you need to download the zip files of each repo and then install locally.

**Comment by olidess** [comment]
I see. Thank you so much for your help!

Best,

Olivier
________________________________
