### ISSUE TITLE
Ability to set base group for factor variables? Issues in interaction i.var1#c.var2

### ISSUE THREAD

**Issue by yilihong** [sergiocorreia/reghdfe#120]
Hello, I am trying to estimate an interaction effect between a dummy and a continuous variable. The baseline of the dummy is 0. However, reghdfe keeps using 1 as baseline, specifying ib0.var does not work either. Here are results from xtreg and reghdfe. Please help.

xtreg:
<img width="944" alt="screenshot 2017-11-10 20 40 05" src="https://user-images.githubusercontent.com/11595258/32685865-58f667ec-c657-11e7-9ed5-20cb73238b03.png">

reghdfe:
<img width="924" alt="screenshot 2017-11-10 20 40 25" src="https://user-images.githubusercontent.com/11595258/32685870-69143064-c657-11e7-9add-54fbcc4fa76a.png">

**Comment by sergiocorreia** [comment]
Quick question, what version of reghdfe are you using, 3.x or 4.x?

**Comment by yilihong** [comment]
@sergiocorreia I am using the current ssc version

**Comment by yilihong** [comment]
. reghdfe, version 
3.2.9 21feb2016

**Comment by sergiocorreia** [comment]
Try with the 4.x version available on Github. The problem is solved there:

```stata
sysuse auto
reghdfe price i.foreign##c.weight , noabsorb nofvlabel // omits domestic (0.foreign)
reghdfe price ib1.foreign##c.weight , noabsorb nofvlabel // omits foreign (1.foreign)
```

```
. reghdfe, version
*! version 4.4.12 10nov2017
```

**Comment by yilihong** [comment]
@sergiocorreia works perfectly. Thank you Sergio.
