### ISSUE TITLE
Concern about t-stat not matching p-value

### ISSUE THREAD

**Issue by OdedGurantz** [sergiocorreia/reghdfe#121]
For background, I am running a simple diff-in-diff using (a) seven states (i.e., statenum); (b) five cohorts that graduated high school from 2012 through 2016 (i.e., year); and (c) 1 "treatment" state that implemented a policy change in 2016. I am doing this with individual-level data (not my favorite idea, but let's ignore that if possible...).

Below is code that dummies for the state and year, omits 2015, and then estimates "impacts" in pre-periods (2012, 2013, 2014) and the real treatment year (2016).

The issue I have is that in the first regression with no clustering, everything looks "fine".

In the second regression the reported t-stat does not match the p-value (though the t-stat equals the estimate divided by the standard error). The clearest example is on the year=2014, the t-stat is 1.85 but the p-value is 0.114 (rather than something less than 0.1). 

Do you know why there is a discrepancy in these values?

--
CODE:

foreach vr in fouryear {
reghdfe `vr' t2012 t2013 t2014 t2016, absorb(statenum year) 
reghdfe `vr' t2012 t2013 t2014 t2016, absorb(statenum year) cluster(statenum)
}

OUTPUT:
. foreach vr in fouryear {
  2. 
. reghdfe `vr' t2012 t2013 t2014 t2016, absorb(statenum year) 
  3. reghdfe `vr' t2012 t2013 t2014 t2016, absorb(statenum year) cluster(statenum)
  4. 
. }
(converged in 5 iterations)

HDFE Linear regression                            Number of obs   =    491,768
Absorbing 2 HDFE groups                           F(   4, 491753) =      42.76
                                                  Prob > F        =     0.0000
                                                  R-squared       =     0.0238
                                                  Adj R-squared   =     0.0238
                                                  Within R-sq.    =     0.0003
                                                  Root MSE        =     0.4654

------------------------------------------------------------------------------
    fouryear |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       t2012 |     .01999   .0048445     4.13   0.000     .0104949     .029485
       t2013 |  -.0063506   .0048388    -1.31   0.189    -.0158345    .0031333
       t2014 |   .0057979   .0049308     1.18   0.240    -.0038663    .0154622
       t2016 |  -.0400876   .0048822    -8.21   0.000    -.0496567   -.0305186
-------------+----------------------------------------------------------------
    Absorbed |     F(10, 491753) =    999.062   0.000             (Joint test)
------------------------------------------------------------------------------

Absorbed degrees of freedom:
---------------------------------------------------------------+
 Absorbed FE |  Num. Coefs.  =   Categories  -   Redundant     | 
-------------+-------------------------------------------------|
    statenum |            7               7              0     | 
        year |            4               5              1     | 
---------------------------------------------------------------+
(converged in 5 iterations)

HDFE Linear regression                            Number of obs   =    491,768
Absorbing 2 HDFE groups                           F(   4,      6) =      61.92
Statistics robust to heteroskedasticity           Prob > F        =     0.0001
                                                  R-squared       =     0.0238
                                                  Adj R-squared   =     0.0238
                                                  Within R-sq.    =     0.0003
Number of clusters (statenum) =          7        Root MSE        =     0.4654

                               (Std. Err. adjusted for 7 clusters in statenum)
------------------------------------------------------------------------------
             |               Robust
    fouryear |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       t2012 |     .01999   .0145528     1.37   0.219    -.0156195    .0555994
       t2013 |  -.0063506   .0065029    -0.98   0.366    -.0222627    .0095615
       t2014 |   .0057979   .0031364     1.85   0.114    -.0018765    .0134724
       t2016 |  -.0400876   .0049097    -8.16   0.000    -.0521013    -.028074
------------------------------------------------------------------------------

Absorbed degrees of freedom:
---------------------------------------------------------------+
 Absorbed FE |  Num. Coefs.  =   Categories  -   Redundant     | 
-------------+-------------------------------------------------|
    statenum |            0               7              7 *   | 
        year |            4               5              1     | 
---------------------------------------------------------------+
* = fixed effect nested within cluster; treated as redundant for DoF computation

**Comment by sergiocorreia** [comment]
Hi Oded,

For completeness' sake, did you found out what was the issue?

Best,
S

**Comment by OdedGurantz** [comment]
Yes, it appears to be an issue common to reported p-values in Stata in the case of clustering. Basically the DoF is treated as the number of clusters (e.g., https://www.stata.com/statalist/archive/2009-04/msg00571.html). So there can be a discrepancy between the reported t-stat and the p-value.
