### ISSUE TITLE
Slightly strange treatment of interactions in controls

### ISSUE THREAD

**Issue by wilbur-t** [sergiocorreia/reghdfe#122]
Hi there Sergio,

The treatment of interacted factor variables by reghdfe is a little inconsistent, and I think this is worth either reconsidering or emphasising in the help files.

When used in the list of control variables, the # operator operates differently to both (a) it's behaviour in the normal regress command, and (b) its behaviour when included in reghdfe's list of absorbed variables. Personally, I didn't realise this, and this lead me to produce erroneous estimates. Having talked to some colleagues, most are surprised by this behaviour and had assumed that # would act as it does in regress.

Here's a code snippet replicating the inconsistency.

```
clear
set obs 10

gen group1 = ceil(2*_n/_N)
gen group2 = 2*ceil(_n/2) == _n

gen x = rnormal()
gen y = rnormal() + x

generate const = 1

reg y x i.group1#i.group2
reg y x i.group1##i.group2
reghdfe y x , absorb(i.group1#i.group2)
reghdfe y x i.group1#i.group2, absorb(const)
```

Thanks for the software! It's incredibly helpful.

**Comment by sergiocorreia** [comment]
Just to be clear, what version are you using? 4.x from GitHub or 3.x from SSC?

**Comment by wilbur-t** [comment]
SSC

**Comment by sergiocorreia** [comment]
The Github version fixes a bug (quirk?) on Stata, so it should be working correctly on 4.x (at least I seem to be getting correct results on the Github version)

**Comment by wilbur-t** [comment]
Ah yes, on the Github version I don't get an issue either.
