### ISSUE TITLE
Document 4.4 changes

### ISSUE THREAD

**Issue by NilsEnevoldsen** [sergiocorreia/reghdfe#123]
Could you drop a note in the recent updates section of Readme.md to briefly explain version 4.4? Thanks!

**Comment by sergiocorreia** [comment]
Done. There are no major changes, just a few tweaks on the Mata internals (that are now better exposed), a few speedups, a few bugfixes that hopefully didn't affect many people (the summarize and nested issues were AFAIK only present on master for a short period), and some code related to another package.

For the most part, reghdfe is as fast as feature-complete as it will probably be on the medium term. One thing that will be important to tackle is better variance-covariance estimators, but we are kinda waiting for theory to improve there.
