### ISSUE TITLE
reghdfe and Information Criterion AIC

### ISSUE THREAD

**Issue by paulp5** [sergiocorreia/reghdfe#124]
I have run a regression using reghdfe and typed "estat ic" afterwards, in order to obtain the Akaike Info criterion (AIC) realization on the empirical model. It seems like reghdfe does not allow "estat ic"; how do I get the AIC? Thanks!

**Comment by sergiocorreia** [comment]
You can compute it by hand, because you have the Log Likelihood (through `e(ll)`). Feel free to also submit pull requests on the `estat` commands.

**Comment by paulp5** [comment]
Alright, thanks a lot for your answer!

Best,
Paul
________________________________
