### ISSUE TITLE
reghdfe crashes in particular model specification

### ISSUE THREAD

**Issue by glennmagerman** [sergiocorreia/reghdfe#125]
Hi Sergio,

I'm using version 4.4.13 31jan2018, and have the following issue:
when estimating a model y = D*alpha + e (i.e. without X*beta), Stata crashes if I don't use the old option (referring to 3.2.6)
Here you can reproduce the issue:
sysuse auto
reghdfe price weight length, absorb(turn trunk) 
reghdfe price, absorb(turn trunk)

**Comment by sergiocorreia** [comment]
What version ftools are you using? (And which version of stata?)

Also, is it a plain crash or some sort of error?

**Comment by sergiocorreia** [comment]
By the way, it does work on my side. These are my specs:

```

. 
. reghdfe, version
c:\ado\plus\r\reghdfe.ado
*! version 4.4.13 31jan2018

Required packages installed?
- ftools            yes

. ftools, version
c:\ado\plus\f\ftools.ado
*! version 2.24.3 24jan2018

Required packages installed?
- moremata          yes

. di c(stata_version)
14.2

. di c(os)
Windows
```

**Comment by glennmagerman** [comment]
Hi Sergio,
Interesting, I seem to have similar specs except for Stata 13.
It'a crash as in Stata exiting while running.
these are the specs: 
. reghdfe, version
/Users/glenn/Library/Application Support/Stata/ado/plus/r/reghdfe.ado
*! version 4.4.13 31jan2018

Required packages installed?
- ftools            yes

. ftools, version
/Users/glenn/Library/Application Support/Stata/ado/plus/f/ftools.ado
*! version 2.24.3 24jan2018

Required packages installed?
- moremata          yes

. di c(stata_version)
13

. di c(os)
MacOSX

**Comment by sergiocorreia** [comment]
I would first suggest two things:

1. Update Stata to the latest version (13.1 in your case)
2. After that, run  `ftools, compile` and `reghdfe, compile`.

Only then, I would try to run something like:

```
log using ....
set trace on
reghdfe ...
```

With the idea of trying to figure out where it crashes.

That said, I'm 99% sure that it should be solved after updating Stata (steps 1 & 2 above) as I've received emails in the past where this happened and was solved by it (on Stata for Linux in this case).

**Comment by glennmagerman** [comment]
OK thanks - I ordered and expect Stata 15 to arrive this week so I'll keep you posted.
Running the compile commands did not work this time (used to work in version 3.x of reghdfe on same machine and setup).

**Comment by sergiocorreia** [comment]
On the mean time, running reghdfe with the `old` version should work (it just runs reghdfe 3 internally)

Best,
S

**Comment by glennmagerman** [comment]
indeed, option old was the way to go until now
FYI - upgraded to Stata 15.1 and running smoothly!
Thanks again for the fantastic piece of code...
