### ISSUE TITLE
Issue in installing reghdfe 4.x on Stata 13.1

### ISSUE THREAD

**Issue by absahay** [sergiocorreia/reghdfe#126]
I am trying to install reghdfe 4.x on  Stata 13.1 using:

cap ado uninstall moresyntax
cap ado uninstall ftools
net install ftools, from("https://github.com/sergiocorreia/ftools/raw/master/src/")

cap ado uninstall reghdfe
net install reghdfe, from("https://github.com/sergiocorreia/reghdfe/raw/master/src/")

if (c(version)<13) cap ado uninstall boottest
if (c(version)<13) ssc install boottest

cap ssc install moremata

source: https://github.com/sergiocorreia/reghdfe

However, I am getting  the following error:
![screen shot 2018-03-03 at 4 40 52 pm](https://user-images.githubusercontent.com/32653524/36939690-327c7e44-1f03-11e8-845d-e704bcbc5e07.png)

Appreciate your help!

**Comment by absahay** [comment]
Thanks much!

**Comment by mcaceresb** [comment]
In case it helps anyone, I'm also on Stata 13 and had this same issue, but it was solved by running:

```stata
 net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")
```

**Comment by sergiocorreia** [comment]
Interesting. It seems that the first link [redirects](https://github.com/processing/processing-docs/issues/532) to githubusercontent, but this might not work correctly on Stata 13. Will try to change the links across the place at some point.

**Comment by rcragun** [comment]
`net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")` no longer works on Stata 13.

**Comment by sergiocorreia** [comment]
Sadly, Stata 13 does not support HTTPS, which is the only way you can download content from Github.

The workaround is to download the zipfile of the release, unzip it  and do a "net install" locally (where the contents of `from()` are in your local drive):

1) 
![image](https://user-images.githubusercontent.com/214056/127793654-a11da639-94ad-4f7c-8d02-ea2fed604556.png)

2)
![image](https://user-images.githubusercontent.com/214056/127793626-6780fc57-d736-4bf9-a0ca-fe378071193d.png)

**Comment by rcragun** [comment]
> Sadly, Stata 13 does not support HTTPS, which is the only way you can download content from Github.

The reason I mentioned it not working on Stata 13 is that I saw the above [comment](https://github.com/sergiocorreia/reghdfe/issues/126#issuecomment-397440348) from @mcaceresb suggesting that HTTPS had worked for them on Stata 13. Either that comment was a mistake or Stata 13 stopped supporting this at some point (or I am just doing something wrong in Stata, which happens often).
