### ISSUE TITLE
Problem with temporary files

### ISSUE THREAD

**Issue by pp2382** [sergiocorreia/reghdfe#127]
Hi,

First of all, thank you so much for your work on reghdfe. The command is incredibly useful. 
I have an issue when I run a regression using reghdfe with many observations, two fixed effects and heterogeneous slopes.
After some preliminary cleaning, reghdfe returns this error: 
"file .../statatmp/St31055.000004 already exists"
FYI, when I use the verbose command, the error appears right after the table summarizing memory usage. Also, I ran this regression on my mac desktop without issue, but this error appears when I run the command on a Linux machine.

Any idea where the issue could come from?

Thanks a lot in advance for your help,
Paul

**Comment by sergiocorreia** [comment]
I'm not really sure what can be causing this. That's a Stata error that *I guess* happens after running `save` with a temporary file, but the current code of reghdfe doesn't do that.

What version of reghdfe are you using? 3 (from SSC) or 4 (from github)? You can find out by typing `which reghdfe`

**Comment by pp2382** [comment]
Hi Sergio,
Thanks for your response. I am using version 3 from ssc. 
Thanks again,
Paul

**Comment by sergiocorreia** [comment]
Can you try to replicate on V4?

**Comment by pp2382** [comment]
Certainly. I have issues installing from Github but I will try as soon as it is resolved.
Thanks
