### ISSUE TITLE
how to use reghdfe and include a two-level fixed effect (industry-by-year fixed effects) in the my difference-in-differences model

### ISSUE THREAD

**Issue by Jamesljj** [sergiocorreia/reghdfe#131]
Hi All, 

I am building a difference-in-differences model, and I want to include a two-level fixed effect (i.e., industry-by-year fixed effects) in it. Could you tell me how I should use reghdfe for this case?

Thank you so much for all your help!

**Comment by sergiocorreia** [comment]
You can just write `absorb(industry#year)`, where industry and year are categorical variables.

**Comment by Jamesljj** [comment]
Thank you very much.
