### ISSUE TITLE
order in absorb() matters？

### ISSUE THREAD

**Issue by stevensqg** [sergiocorreia/reghdfe#132]
webuse nlswork, clear
reghdfe ln_w grade age ttl_exp tenure not_smsa south , absorb(idcode year occ)
reghdfe ln_w grade age ttl_exp tenure not_smsa south , absorb(occ idcode year)

Note that in the first regression, "grade" is omitted since it does not vary for the same "idcode". But in the second regression where I only change the order in "absorb()", "grade" is not dropped. It has a coefficient with p-value = 1.

**Comment by sergiocorreia** [comment]
Quick question: what version of reghdfe are you using?

**Comment by stevensqg** [comment]
Hi, I am using Stata 14. I just "ssc install reghdfe" again. Still the same thing happened.

**Comment by sergiocorreia** [comment]
It's probably a numerical issue when trying to detect collinear variables (it's nontrivial to do so with reghdfe, as we need to detect when a demeaned variable is close enough to zero, while avoiding false positives).

That said , the code on GitHub (version 4) should be much better in dealing with this.

**Comment by stevensqg** [comment]
Thanks for the solution! It works well.
