### ISSUE TITLE
assert_msg() already exists

### ISSUE THREAD

**Issue by reduarte** [sergiocorreia/reghdfe#134]
Hi Sergio, thank you for this very useful command. It was working great until today when I started getting this error and now I can no longer run the reghdfe command. Here's the output I get from a simple regression with a dependent variable and one independent variable: 

. reghdfe INCcoal_sh WStitlings, a(IDn i.year) vce(cl orden) 
reghdfe.assert_msg() already exists
(1792 lines skipped)
(error occurred while loading reghdfe.ado)

Any ideas on how I can solve this issue?

**Comment by reduarte** [comment]
Just to make sure it is clear, this line of code previously worked, now for some reason it does not

**Comment by sergiocorreia** [comment]
Can you try the following lines?

```
which reghdfe
which ftools
reghdfe, compile
ftools, compile
discard
pr drop _all
```

**Comment by reduarte** [comment]
Thank you for the quick response Sergio! It turns out that after I restarted my laptop, the line of code worked again. I remember reading that in of the other issue threads here! 

In any case, these are the outputs once I run those lines:

> . which reghdfe
> c:\ado\plus\r\reghdfe.ado
> *! reghdfe 3.2.9 21feb2016
> *! Sergio Correia (sergio.correia@duke.edu)
> 
> . 
> . which ftools
> command ftools not found as either built-in or ado-file
> r(111);
> 
> . 
> . reghdfe, compile
> last estimates not found
> r(301);
> 
> . 
> . ftools, compile
> command ftools is unrecognized
> r(199);
> 
> . 
> . discard
> 
> . 
> . pr drop _all

**Comment by sergiocorreia** [comment]
Interesting... I also recall those threads but can't seem to easily replicate the problem!
