### ISSUE TITLE
How p-value is calculated

### ISSUE THREAD

**Issue by xr2111** [sergiocorreia/reghdfe#135]
I have run into some issues with the p-value reported by the program: I run a two-way fixed effects model include an individual fixed effect and a course fixed effects and the standard errors are two-way clustered at individual and course level. Here are the results reported:

> reghdfe grade_first_gk adjunct##k12 i.reportingterm ///
>                       facetoface enrollment crattempt ///
>                       age_2012 master_instr doctor_instr fulltime_instr ///
>                       exp_course1 exp_course2 exp_course3 exp_deved1 exp_deved2 exp_deved3,	///
>                      absorb(student_nid subject course_nid) vce(cluster student_nid subject	course_nid) 

> (dropped 27952 singleton observations)
> (converged in 91 iterations)

> HDFE Linear regression                            Number of obs   =     46,968
>Absorbing 3 HDFE groups                           F(  43,      1) =       3.62
>Statistics robust to heteroskedasticity           Prob > F        =     0.3982
>R-squared       =     0.7215
>Number of clusters (student_nid) =     23,484     Adj R-squared   =     0.4354
>Number of clusters (subject) =          2         Within R-sq.    =     0.0075
>Number of clusters (course_nid) =        268      Root MSE        =     0.9662

>(Std. Err. adjusted for 2 clusters in student_nid subject course_nid)

>Robust
>grade_first_gk       Coef.          Std. Err.      t           P>t     [95% Conf. Interval]

>1.adjunct             -.0596591   .0241669    -2.47   0.245    -.3667281    .2474099
>1.k12                    .0390046    .023932      1.63    0.350    -.2650807    .3430899

Where the t value for the variable "1.adjunct" is -2.47 but the p value is 0.245.

I'm wondering how the p value was calculated and whether this is a mistake?

**Comment by sergiocorreia** [comment]
`reghdfe` doesn't directly calculate P-values, but Stata does. That said, the pvalues you report are indeed the correct ones, because you only have two degrees of freedom (due to your clusters)
