### ISSUE TITLE
predict, xbd doesn't recognized changed variables

### ISSUE THREAD

**Issue by simonheb** [sergiocorreia/reghdfe#138]
When I change the value of a variable used in estimation, predict is supposed to give me fitted values based on these new values. predict after reghdfe doesn't do so. Example:

```
clear 
set obs 100
gen x1 = rnormal()
gen x2 = rnormal()
gen d = mod(_n,2)
gen y=x1+x2+d+rnormal()

preserve //expected behaviour
	reg y c.x1 c.x2 i.d  
	predict yhat1_reg 
	replace x1 = -1
	predict yhat2_reg
	scatter yhat1_reg yhat2_reg, name(s_reg,replace)
restore

preserve //reghdfe behaviour
	reghdfe y c.x1 c.x2 , a(d) resid  
	predict yhat1_reghdfe, xbd  
	replace x1 = -1
	predict yhat2_reghdfe, xbd 
	scatter yhat1_reghdfe yhat2_reghdfe, name(s_reghdfe,replace)
restore
```
Am I getting something wrong or is this a bug? (This only happens in combination with the xbd option

Clarification: A previous issue i filed (https://github.com/sergiocorreia/reghdfe/issues/137) was related but is different and was merely because I used an old version of reghdfe. This time I'm using version 5.2.0 17jul2018

**Comment by simonheb** [comment]
This works for me as a quick and dirty workaround:

```
	reghdfe y c.x1 c.x2 , a(FE1=d)  
	predict yhat1_reghdfe_XB
	gen yhat1_reghdfe = yhat1_reghdfe_XB+FE1
	replace x1 = -1
	predict yhat2_reghdfe_XB
	gen yhat2_reghdfe = yhat2_reghdfe_XB+FE1
	scatter yhat1_reghdfe yhat2_reghdfe, name(s_reghdfe,replace)
```
But I'd somehow expect this to be the default behaviour when I use ,xbd

**Comment by simonheb** [comment]
I see. I was trying to predict outcomes in absence of treatment in an student-level RCT, the fixed effects were for schools and years. So they were identified from the control group and I think theoretically the idea is fine. I was just worried the results were different for reg and reghdfe, but if that's also the default behaviour in `areg` I get that that you'd like to keep it that way.

**Comment by sergiocorreia** [comment]
That makes sense. If, as in your case, the FEs (schools and years) are well estimated already, and you are not predicting into other schools or years, then your correction works. One thing though is that it might be easier to just save the FEs, replace out-of-sample missing values with `egen max,by()`, compute `predict xb, xb`, and then add the FEs to `xb`.
