### ISSUE TITLE
Omitted categories in reghdfe 3.2.9 versus reghdfe 5.2.2

### ISSUE THREAD

**Issue by tatyanaderyugina** [sergiocorreia/reghdfe#141]
Hi Sergio,

I'm running the following specification (same as in another issue):  
    reghdfe PM25_conc i.poll_cluster#ib0.ang_range, absorb(stuff)

There are about 100 poll_cluster values (1-100) and 4 ang_range values (0, 90, 180, 270). I would like the ang_range=0 value to be omitted within each poll_cluster, thus the "ib0." notation.

reghdfe 3.2.9 omits poll_cluster=1 entirely, which is wrong but easily fixable because I can add the interactions manually. It seems to get the other omitted categories exactly right.

reghdfe 5.2.2 does not omit poll_cluster=1, which is great, BUT it does not always drop the ang_range=0 value within each poll_cluster. In some cases, it drops the wrong category (e.g., ang_range=90). Sometimes it drops more than one with a poll_cluster and then none in another poll_cluster. Is there an easy way for you to fix this, especially since it (almost) was working before? 

Attached log file shows the same regression with 3.2.9 (first one, missing categories for poll_cluster=1 manually added) and then with 5.2.2 (second one).
[OmittedCategories.log](https://github.com/sergiocorreia/reghdfe/files/2257643/OmittedCategories.log)

**Comment by sergiocorreia** [comment]
Hi Tatyana,

Sorry for the late reply. With "ib0", Stata will omit the 0.ang_range variable, but will not omit the interaction of that variable with other factors, so reghdfe's behavior is probably in line with that of regress and other commands.

One option might be to try to do `i.poll_cluster##ib0.ang_range` (add an extra "#"). On a dataset I tried, that gave me saner results. 

Else, if you have a smaller version of the dataset that you can share, or any other dataset where I can reproduce the issue, it would be super useful

**Comment by sergiocorreia** [comment]
I'm trying this on my laptop, so I'm only working on subsamples based on poll_cluster, but I can't replicate the problem. 

----

I'm also revisiting your original log file, and most of the results there are actually unsurprising:

> reghdfe 5.2.2 does not omit poll_cluster=1, which is great, BUT it does not always drop the ang_range=0 value within each poll_cluster. In some cases, it drops the wrong category (e.g., ang_range=90).  Sometimes it drops more than one with a poll_cluster and then none in another poll_cluster

We can see this in the four regressors with `poll_cluster=2`, where none are dropped. However, if you see absorb() table, notice that you didn't had 400 categories of `poll_cluster#L1ang_range`, so maybe there was no category with `poll_cluster=2` in your fixed effects (after dropping singletons)?

Then, dropping multiple regressors within a poll_cluster is also possible (e.g. with `poll_cluster=28`) because the LHS might be perfectly explained by the fixed effects in those categories.

The only puzzling thing is that it drops `94  90` when we would have expected `94   0` to be dropped. But again, that code is outside reghdfe and part of Stata, so I don't have much control there.

----

Regarding your latest dataset, can you try adding a `poll_cluster` fixed effect before adding the `poll_cluster#L1ang_range` interactions? That might help you with the poll_cluster that gets added.

**Comment by psvatsa** [comment]
I wanted to understand the following and not sure if the two are related: 
`reghdfe YVAR  ib19dif##i.treat controls, cluster(clustervar) absorb(year panel-id)` is the code it produces the output 
```
 dif#treat |
       10 1  |   .1039422   1.283463     0.08   0.936    -2.479535     2.68742
       11 1  |  -.3399909   1.231326    -0.28   0.784    -2.818522     2.13854
       12 1  |   .7414249    1.05297     0.70   0.485    -1.378094    2.860944
       13 1  |   .6107571   1.295674     0.47   0.640      -1.9973    3.218814
       14 1  |     .39356   1.175573     0.33   0.739    -1.972745    2.759865
       15 1  |   2.063219   1.775728     1.16   0.251    -1.511136    5.637575
       16 1  |   .9777427   1.018561     0.96   0.342    -1.072515       3.028
       17 1  |   2.271153   1.020286     2.23   0.031     .2174245    4.324881
       18 1  |   1.978524   1.246361     1.59   0.119    -.5302711    4.487318
       20 1  |   -4.64421   1.556187    -2.98   0.005    -7.776653   -1.511768
       21 1  |  -5.596979   1.362165    -4.11   0.000    -8.338875   -2.855082
       22 1  |  -4.860838   1.235728    -3.93   0.000    -7.348229   -2.373447
       23 1  |  -3.936607   1.290388    -3.05   0.004    -6.534023   -1.339191
       24 1  |  -5.136231   1.183745    -4.34   0.000    -7.518986   -2.753475
       25 1  |  -4.734167   1.020978    -4.64   0.000    -6.789289   -2.679045
       26 1  |  -5.728412   1.284677    -4.46   0.000    -8.314334   -3.142491
       27 1  |  -5.731197   1.315701    -4.36   0.000    -8.379565   -3.082828
       28 1  |   1.189435   1.104055     1.08   0.287    -1.032912    3.411782
       29 1  |   1.532176   1.790198     0.86   0.397    -2.071306    5.135658
       30 1  |  -.1506353   .6733853    -0.22   0.824     -1.50609    1.204819
       31 1  |          0  (omitted)
```
 seems it doesn't matter if it were ib19, it could every well have been
```
Code:
reghdfe YVAR  ib16dif##i.treat controls, cluster(clustervar) absorb(year panel-id)
I get the same coefficients (i.e. relative to dif = 31) why does stata choose the last to omit.
Code:
       10 1  |  -.8738004   .9079232    -0.96   0.341    -2.701355    .9537542
       11 1  |  -1.317734   .8320499    -1.58   0.120    -2.992563     .357096
       12 1  |  -.2363178   .8177951    -0.29   0.774    -1.882454    1.409818
       13 1  |  -.3669855   1.102138    -0.33   0.741    -2.585474    1.851503
       14 1  |  -.5841827    .752915    -0.78   0.442    -2.099722    .9313567
       15 1  |   1.085477   1.601499     0.68   0.501    -2.138174    4.309127
       17 1  |    1.29341   .8236691     1.57   0.123    -.3645499     2.95137
       18 1  |   1.000781   1.044988     0.96   0.343    -1.102671    3.104233
       19 1  |  -.9777427   1.018561    -0.96   0.342       -3.028    1.072515
       20 1  |   -4.64421   1.556187    -2.98   0.005    -7.776653   -1.511768
       21 1  |  -5.596979   1.362165    -4.11   0.000    -8.338875   -2.855082
       22 1  |  -4.860838   1.235728    -3.93   0.000    -7.348229   -2.373447
       23 1  |  -3.936607   1.290388    -3.05   0.004    -6.534023   -1.339191
       24 1  |  -5.136231   1.183745    -4.34   0.000    -7.518986   -2.753475
       25 1  |  -4.734167   1.020978    -4.64   0.000    -6.789289   -2.679045
       26 1  |  -5.728412   1.284677    -4.46   0.000    -8.314334   -3.142491
       27 1  |  -5.731197   1.315701    -4.36   0.000    -8.379565   -3.082828
       28 1  |   1.189435   1.104055     1.08   0.287    -1.032912    3.411782
       29 1  |   1.532176   1.790198     0.86   0.397    -2.071306    5.135658
       30 1  |  -.1506353   .6733853    -0.22   0.824     -1.50609    1.204819
       31 1  |
0 (omitted)
```

**Comment by psvatsa** [comment]
As in the two outputs are the same, but they are both relative to dif == 31 and not dif == 19 which is what I wanted?

**Comment by sergiocorreia** [comment]
The first one is also omitting dif=19. Most likely, because of the fixed effects, two of the dummies end up being dropped (19 and 31, etc)

**Comment by psvatsa** [comment]
So both these are relative to dif = 31 not dif = either 16 or 19 , if  I keep dif between 15 and 26 the 26 will be dropped and all are then shown relative to 26, why not 19

**Comment by sungyupjung** [comment]
I am having the same issue. I would like to why the last one gets dropped out
