### ISSUE TITLE
3499  create_mask() not found

### ISSUE THREAD

**Issue by felixholub** [sergiocorreia/reghdfe#142]
When I run:
```
sysuse auto, clear
reghdfe price mpg, noabs
```
I get the error:
```
FixedEffects::save_touse():  3499  create_mask() not found
                 <istmt>:     -  function returned error
r(3499);
```
Happens on my Win and my Linux machine. Stata is version 15 and

```
. reghdfe, version
/home/username/ado/plus/r/reghdfe.ado
*! version 5.2.8 06aug2018

Required packages installed?
- ftools            yes
```

**Comment by sergiocorreia** [comment]
Can you check if you have the latest ftools installed? That version was created on ftools 2.30.2 from a few weeks ago (https://github.com/sergiocorreia/ftools/commit/c8c3e1d5126564a6cc737d8bf568b106cff3375f), but the minimum version check is still set at 2.30.1: https://github.com/sergiocorreia/reghdfe/blob/master/src/reghdfe.ado#L49

Might also be worth it to run `reghdfe, compile` to create updated `.mlib` files.

**Comment by felixholub** [comment]
Indeed, I had version 2.30.1 is running.
I usually update packages with ```adoupdate, update```, which currently does not catch the most recent version of ftools. With a manual installation it works. Thank you!
