### ISSUE TITLE
F-statistics in reghdfe 3.2.9 versus reghdfe 5.1.2 

### ISSUE THREAD

**Issue by tatyanaderyugina** [sergiocorreia/reghdfe#143]
Hi Sergio,

We are running an IV specification with reghdfe. For the same regression, reghdfe 3.2.9 is able to calculate F-statistics (which look reasonable), but reghdfe 5.1.2 gives a -ranktest- error. I thought it might be because of issues with clustered standard errors, but the new reghdfe fails to calculate these statistics even with homoskedastic errors. Given that the old reghdfe seems to be doing well, I wonder if something can be done to improve the new reghdfe.

Here's the log file. First two regressions are with 3.2.9 (same regression, but either robust or homoskedastic errors), next three are with 5.1.2 (clustered, robust, and homoskedastic errors). The coefficients are also slightly different because 3.2.9 omits categories differently, as we discussed in a previous issue. Old reghdfe with clustered standard errors not shown because I ran it earlier, but it behaves similarly to the old reghdfe with robust. 
[New_reghdfe_test_edited.log](https://github.com/sergiocorreia/reghdfe/files/2283106/New_reghdfe_test_edited.log)

(we're trying to figure out whether to switch to the new reghdfe, which is why you're seeing a lot of these types of issues from me)

**Comment by sergiocorreia** [comment]
`ivreghdfe` outsources the *identification tests to `ivreg2` (Kleibergen-Paap,  Cragg-Donald).  I would try a few things:

- Be sure that a similar `ivreg2` command without any fixed effects works correctly (it might not, if `ivreg2` or `ranktest` are from an older version)
- See the first stage results (option `first` I think?) to have a better idea of what's the issue.

Finally, note that you can also run 3.2.9 while 5.x is installed if you use the `old` version (I added that option to make testing easier, but it might be useful if there is something that the new version doesn't do).

Best,
S
