### ISSUE TITLE
Stata crashes with large estimation

### ISSUE THREAD

**Issue by adamfms** [sergiocorreia/reghdfe#145]
Hello Sergio, 

I am having problems when running reghdfe with a large (50 million+) number of observations. The command runs for a while and reports having dropped singletons and sometimes that the estimator has converged. However, Stata then reports that it needs to close (or debug, but debugging doesn't work). 

Any ideas to get this working? areg works fine but I would like correct standard errors (and have the options to absorb multiple fixed effects and have 2-way clustered SEs). 

Thanks for your help. 

Best, 

Adam

These are my specs: 

```
. reghdfe, version
c:\ado\plus\r\reghdfe.ado
*! version 5.2.9 06aug2018

Required packages installed?
- ftools            yes

. ftools, version
c:\ado\plus\f\ftools.ado
*! version 230.3 02aug2018

Required packages installed?
- moremata          yes

. di c(stata_version)
15

. di c(os)
Windows
```

**Comment by sergiocorreia** [comment]
Hi Adam,

Sorry for the late reply. reghdfe can't directly make Stata crash (no C code, etc) so this is almost surely a problem with Stata itself (or Windows)

The first thing I would do is update Stata to 15.1.

If that doesn't work, run reghdfe with the verbose(1) option, and use `log using..` to see where the crash happened. My guess is somewhere that required a lot of memory.

Finally, a less probable option is something related to your computer. For instance, if your RAM is corrupted then it might only fail if you are using a lot of memory (again, that's quite unlikely but I've seen it happen)
