### ISSUE TITLE
Issue with if statement

### ISSUE THREAD

**Issue by adrenik** [sergiocorreia/reghdfe#147]
Hi Sergio,

I'm trying to estimate a simple equation with fixed effects. I have a string variable called type_post that splits the data into 3 groups. I want to estimate the equation for each value of type_post. When I run:

_levelsof type_post, local(typepost)
foreach tp of local typepost {
  reghdfe deltap_lc L(0/1).delta_nxr if type_post == "`tp'", absorb(numid) robust
}_

I get the error message "X ambiguous abbreviation", where X is one of the values of type_post given by `tp'. If instead I run 

_levelsof type_post, local(typepost)
foreach tp of local typepost {
  reghdfe deltap_lc L(0/1).delta_nxr if inlist(type_post,"`tp'"), absorb(numid) robust
}_

it works without errors. I also recently updated the package. Any idea what is going on? Thanks!

**Comment by sergiocorreia** [comment]
Just to be sure, what versions of reghdfe and ftools are you using?

**Comment by adrenik** [comment]
I'm sorry to ask you this, but how can I check this?

**Comment by sergiocorreia** [comment]
You can type "which reghdfe" and "which ftools"
