### ISSUE TITLE
command reghdfe_store_alphas is unrecognized

### ISSUE THREAD

**Issue by Davidxu2016** [sergiocorreia/reghdfe#148]
Hi,

I am using reghdfe to estimate a linear OLS model with three-way FEs and clustered standard errors. When I run the command, I got the following report

> (dropped 9700 singleton observations)
(MWFE estimator converged in 65 iterations)
command reghdfe_store_alphas is unrecognized

I could not find command reghdfe_store_alphas in Stata. The version I am using is

> . which reghdfe
c:\ado\plus\r\reghdfe.ado
*! version 5.2.9 06aug2018

and

>  which ftools
c:\ado\plus\f\ftools.ado
*! version 2.30.3 02aug2018

**Comment by sergiocorreia** [comment]
Hi David,

That do-file is currently missing in the SSC version; so in the mean time please use the Github version.

Best,
Sergio

**Comment by psvatsa** [comment]
I got the error 

command reghdfe_store_alphas is unrecognized

which reghdfe

```
c:\ado\plus\r\reghdfe.ado
*! version 5.7.1 20mar2019
```

. which ivreghdfe

```
c:\ado\plus\i\ivreghdfe.ado
*! ivreghdfe 1.0.0  07jul2018
*! this just adds absorb() to this code:
*! ivreg2 4.1.10  9Feb2016
*! authors cfb & mes
*! see end of file for version comments
```

copy pasted the following to install ivreghdfe 
```
* Install ftools (remove program if it existed previously)
cap ado uninstall ftools
net install ftools, from("https://raw.githubusercontent.com/sergiocorreia/ftools/master/src/")

* Install reghdfe
cap ado uninstall reghdfe
net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")

* Install boottest (Stata 11 and 12)
if (c(version)<13) cap ado uninstall boottest
if (c(version)<13) ssc install boottest

* Install moremata (sometimes used by ftools but not needed for reghdfe)
cap ssc install moremata

* Install ivreg2, the core package
cap ado uninstall ivreg2
ssc install ivreg2

* Finally, install this package
cap ado uninstall ivreghdfe
net install ivreghdfe, from(https://raw.githubusercontent.com/sergiocorreia/ivreghdfe/master/src/)
```

**Comment by sergiocorreia** [comment]
There are two possible solutions for this:

1. install the latest version of reghdfe
2. Type "reghdfe, compile"

Either should work

**Comment by psvatsa** [comment]
so this version 5.7.1 20mar2019 of reghdfe is not the latest version ? 

I did reghdfe, compile and tried receive same error

**Comment by psvatsa** [comment]
When I try to install ivreghdfe using the instructions on your page, the following code is executed  
```
Install reghdfe
cap ado uninstall reghdfe
net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")
```
and so I guess the latest reghdfe is isntalled 
and the same with ivreghdfe 
```
cap ado uninstall ivreghdfe
net install ivreghdfe, from(https://raw.githubusercontent.com/sergiocorreia/ivreghdfe/master/src/)
```

over and above these I compile reghdfe 
is the  07jul2018 compatible with c:\ado\plus\r\reghdfe.ado
*! version 5.7.1 20mar2019

**Comment by sergiocorreia** [comment]
That's unexpected.

- are you running on a server or any setup where multiple versions might be installed?
- If you uninstall and reinstall reghdfe (without the "cap", to ensure no errors get silently ignored) is the problem fixed?
- is the reghdfe_store_alphas.ado file installed on the hard drive ("which...")?

**Comment by psvatsa** [comment]
> That's unexpected.
> 
> * are you running on a server or any setup where multiple versions might be installed? 
Yes. Stata both 14.2 and 15.1  are both installed. Not server, desktop

> * If you uninstall and reinstall reghdfe (without the "cap", to ensure no errors get silently ignored) is the problem fixed? No. 

> * is the reghdfe_store_alphas.ado file installed on the hard drive ("which...")? No :(
```
```
which  reghdfe_store_alphas
command reghdfe_store_alphas not found as either built-in or ado-file
```



```
