### ISSUE TITLE
acceleration method

### ISSUE THREAD

**Issue by sergiocorreia** [sergiocorreia/reghdfe#15]
Currently, map_solve() is good enough with conjugate gradient and symmetric kaczmarz, so I don't have any dataset that requires more than a few iterations to converge.

Also, most synthetic benchmarks are "easy to solve" in terms of overall connectivity of the underlying graph.

Instead, I need a hard-to-solve dataset (basically, just the FEs) in order to tune-up the acceleration.

There are two potential improvements:
1) combine kaczmarz with cimmino (because one method seems better earlier on, and the other at the end)

2) Apply the GT preconditioner

**Comment by laszlosandor** [comment]
Maybe this is related. Raj had bad experience with other tools offering
multiple FEs before, saying those never converge on IRS data. Is this
superior?

**Comment by sergiocorreia** [comment]
Yes. Some papers show that alternative accelerations can be i) slower than no accelerations at all, and ii) may even fail to converge due to overshooting. Also, without accelerations, the convergence can be arbitrarily slow.

The latest reghdfe has something really interesting in that you can choose both the acceleration and transform among several options, and that it's reaaaally easy to code new transforms/accelerations. I set as default the one that performed better in my data (symmetric kaczmarz transform with conjugate gradient acceleration).

The only limitation is that the subroutine that saves the fixed effects will still use the slower methods, although there are not many reasons for wanting that (given the new resid() option).

If you can talk to him that would be great. I don't need the y or x variables, I just need the "FE" structure of the problem (basically, the absorb() variables than can be trivially anonimized).
