### ISSUE TITLE
Reghdfe difference in differences

### ISSUE THREAD

**Issue by pdeffebach** [sergiocorreia/reghdfe#152]
My specification was off, so there is no bug in `reghdfe`. Thank you for the great package!

**Comment by simonheb** [comment]
I do think your specification is off. You seem to be interested in the coefficient of the "arrest" variable, and at the same allow the coefficient to differ by values of `day`. I don't know exactly what your variables measure, but if it's a diff-in-diff, usually the interaction would be the thing of interest.

But from what you reveal about your data the behavior of reghdfe is exactly what it is supposed to be.

**Comment by pdeffebach** [comment]
You are correct.
