### ISSUE TITLE
HAC correction

### ISSUE THREAD

**Issue by ahillklsp** [sergiocorreia/reghdfe#155]
I updated my installation to the latest version and when I try to perform a HAC correction as specified online  (vce(cluster clustervars, bw(#)) it tells me that this "VCE options not supported: bw(4)"

**Comment by sergiocorreia** [comment]
Hi Austin,

Good catch! (by the way, you found that on the website, helpfile, or on github.com? I haven't finished updating the instructions to the new version of reghdfe)

On earlier versions of reghdfe, I was able to use the HAC corrections by calling `ivreg2`. However, all the ivreg2-related code now lies in the `ivreghdfe` package (which makes my life a lot easier). `ivreghdfe` (avaliable on github or ssc) can be used in the same way as `ivreg2`, but with an extra `absorb()` option that partials out the fixed effects. Thus, you need to do this:

```stata
* Create sample code with a time dimension
sysuse auto, clear
bys turn: gen time = _n
xtset turn time

* Call older version of reghdfe, just to be sure we get the same results
reghdfe price weight, a(turn) vce(cluster time, bw(2)) old

* Call ivreghdfe
ivreghdfe price weight, a(turn) cluster(time) bw(2)
```

Best,
Sergio

**Comment by ahillklsp** [comment]
Hello Sergio,

Those instructions were on your personal website. Thank you so much for the prompt reply and the helpful fix and example code (and of course for reghdfe and ivreghdfe). Please let me know if there is any other information I can provide.


Sincerely,

Austin Hill-Kleespie
Finance Ph.D. Candidate
David Eccles School of Business
University of Utah
BUC 450 A
Email: austin.hill-kleespie@eccles.utah.edu<mailto:austin.hill-kleespie@eccles.utah.edu>
Access Papers at: https://ssrn.com/author=2325681

**Comment by sergiocorreia** [comment]
Great! I'll try to update the website instructions at some point in the near future.

Best,
Sergio
