### ISSUE TITLE
IV not working with new update

### ISSUE THREAD

**Issue by christophermace** [sergiocorreia/reghdfe#156]
Trying to run:

sysuse auto
reghdfe price weight (length=head), absorb(rep78)

throws a "parentheses unbalanced" error (r(132))

Love the program!

**Comment by sergiocorreia** [comment]
Hi Christoph,

Please use this command: https://github.com/sergiocorreia/ivreghdfe/

You can also use the `old` option of reghdfe, which calls the older version of reghdfe.

**Comment by christophermace** [comment]
Hi Sergio,

Ah.  I now see my stupid mistake.  Sorry to bother.  Love the program, thank you for making it!

Best,

Christopher Mace
David Eccles School of Business
Department of Finance, PhD Candidate
University of Utah
BUC 450A
801.584.9653
chris.mace@eccles.utah.edu<mailto:chris.mace@eccles.utah.edu>
SSRN page: http://ssrn.com/author=2498369
