### ISSUE TITLE
Unable to install: file not found: ftools,.ado

### ISSUE THREAD

**Issue by kylebarron** [sergiocorreia/reghdfe#157]
The install instructions on the README don't work for me. Upon running `reghdfe, compile`, I get 
```
file not found: ftools,.ado
r(123);
```

![image](https://user-images.githubusercontent.com/15164633/49771229-2df3cd00-fcb6-11e8-9ad1-c803e3886592.png)

I'm similarly unable to install when using the Stata terminal directly (with both 14.2 and 15.1) so it's not some fault of using Stata through Jupyter.

![image](https://user-images.githubusercontent.com/15164633/49771326-9478eb00-fcb6-11e8-86f7-a443687c24b8.png)
![image](https://user-images.githubusercontent.com/15164633/49771333-98a50880-fcb6-11e8-80ec-a576c1c5960f.png)

How does `reghdfe, compile` search for the ftools library?

**Comment by sergiocorreia** [comment]
Are you running this on a server where adopath is managed by someone else, such as the NBER servers? Based on previous users' comments, this seems to be a problem with the server's configuration and not with reghdfe or Jupyter.

In particular, Stata allows you to install reghdfe on multiple places, such as `plus` and `personal`. So you installed the files on your own path, but then Stata calls the files previously installed on personal. One of the reasons why I suspect this is because the dot+comma bug is an old one that I fixed ages ago (it was just a typo in the error message), so it shouldn't be possible for you to see that error if you just downloaded it.

I'm pasting below a solution that worked for the NBER servers, and might be useful for you:

> If anyone else ever asks you about this, feel free to forward them the set of steps described below, which fixed the problem.
> 
> 1. Create a folder in your personal home directory where you would like to install new do files. For example, I created "/disk/homedirs/nber/karger/programs/plus"
> 
> 2. In a do file, define a global:
> 
> global plusdir "/disk/homedirs/nber/karger/programs/plus/"
> 
> 3. Now, tell Stata to download new do files to that folder by re-assigned the 'PLUS' path to that directory with this line:
> 
> sysdir set PLUS $plusdir
> 
> 4. Install fresh copies of ftools and reghdfe from github:
> 
> capture ado uninstall ftools
> net install ftools, from("https://github.com/sergiocorreia/ftools/raw/master/src/")
> 
> capture ado uninstall reghdfe
> net install reghdfe, from("https://github.com/sergiocorreia/reghdfe/raw/master/src/")
> 
> 5. Lastly, inform Stata, using adopath, that it should FIRST look in $plusdir before looking for ado files in the base Stata path which all NBER users use:
> 
> adopath ++ $plusdir
> 
> 6. At this point in your do file, you should be able to call reghdfe without any issues.

Let me know if it works, and **please** also let someone at the NBER know, because I'm getting a bit tired of doing unpaid IT support for them.

Best,
Sergio

**Comment by kylebarron** [comment]
First I want to emphasize that I searched for the error in the Github issues, and looked through a few other installation error issues and only posted when I didn't find anything relevant. Hopefully this thread will be helpful for future questions.

I am working on the NBER servers, and I'll contact the IT manager.

Personally, at first glance this seems like a Stata bug. If the default installation place for new packages is `PLUS`, then `PLUS` should be the first folder on the ado-path, and vice versa if `PERSONAL`.

**Comment by kylebarron** [comment]
Haha personally I get annoyed when I get support requests by email and ask them to submit a Github issue, partially for future visitors.

I didn't actually check first if there was a system-wide reghdfe installation, but given the dates of your recent releases, they almost certainly wouldn't have the newest version.

**Comment by feenberg** [comment]
I just learned about this problem today - not sure why no one has mentioned it to me yet. I was able to install (but not compile) the programs for all users after downloading from github. I get the following message when I compile:

`. net set other /homes/site/etc/stata/ado.nber

. ftools,compile
(compiling lftools.mlib for Stata 15.1)
cannot save compiled Mata file in sysdir_plus (~/ado/plus/)
cannot save compiled Mata file in sysdir_plus (~/ado/personal/)
file "lftools.mlib" not found
r(601);`

It appears that without this step, the program is still usable, but a compiled copy is created and saved in each users personal ado directory. Any suggestions appreciated.

Daniel Feenberg
NBER

**Comment by sergiocorreia** [comment]
When compiling, ftools will try to save the mlib file in three places: plus, personal, and the current path

https://github.com/sergiocorreia/ftools/blob/master/src/ms_compile_mata.ado#L158

Are you able to save in any of those paths when running Stata? Note that every user does not need to compile the file, you can just manually place the two mlib files into the "L" folder of plus (lftools.ado, lreghdce.ado) and it will work.
