### ISSUE TITLE
e(version) (=macro output of "reghdfe, version") no longer available

### ISSUE THREAD

**Issue by lucasmation** [sergiocorreia/reghdfe#158]
I am trying to use a 3rd party program (pc_simulate) that made reference to `e(version)`, which seems to have been removed from the latest version of reghdfe. This, in turn, breaks that 3rd party program.

Was `e(version)` removed on purpose? 

I am having trouble accessing the version that is only displayed in the screen and using that information as a replacement for `e(version)` in that program.

```
reghdfe, version
ereturn list
```

**Comment by sergiocorreia** [comment]
I'm not even aware of `reghdfe, version` saving anything on `e()`.

That said, you could just use the `ms_get_version` command from `ftools` (which you already have, as it's used by reghdfe to ensure it's not using an outdated version of ftools). This is how to use it:

```
ms_get_version reghdfe
di "`package_version'"
di "`version_number'"
di "`version_date'"

ms_get_version reshape
di "`package_version'"
di "`version_number'"
di "`version_date'"
```

Note that it should work with most packages that have defined their version on the first line.

**Comment by lucasmation** [comment]
Tks @sergiocorreia !!!!

`version_number` and `version_date` are returning empty strings. 

But I can parse `package_version`
```
. reghdfe, version
c:\ado\plus\r\reghdfe.ado
*! version 5.2.9 06aug2018

Required packages installed?
- ftools            yes

. 
. ms_get_version reghdfe

. 
. di "`package_version'"
5.2.9 06aug2018

. 
. di "`version_number'"


. 
. di "`version_date'"

```

**Comment by sergiocorreia** [comment]
Cool! I think those two were added on a recent update, so I think they should work if you update ftools. (Also, try updating reghdfe to the github version if you have Stata 15+)

**Comment by lucasmation** [comment]
updating worked. Tks again!
