### ISSUE TITLE
"3021 class compiled at different times" when using "absorb(newvar = varname)"

### ISSUE THREAD

**Issue by simonheb** [sergiocorreia/reghdfe#165]
I'm running the latest Stata and reghdfe and ftools (see below). When I run reghdfe, making use of the option to safe the fixed effect estimates I get the following error:

```
(MWFE estimator converged in 1 iterations)
                 <istmt>:  3021  class compiled at different times
r(3021);
```

Easiest code to replicate the issue:
```
sysuse auto.dta
reghdfe price make , a(fe1=foreign)
```

Last lines of ouput prior to error when `set tracedepth 10`

```
    - qui replace `d' = `e(depvar)' - `d' - `e(resid)' if e(sample)
    = qui replace __000006 = price - __000006 - __temp_reghdfe_resid__ if e(sample)
    - mata: HDFE.store_alphas("`d'")
    = mata: HDFE.store_alphas("__000006")
                 <istmt>:  3021  class compiled at different times
```

Info on my software versions:

```
. net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")
checking reghdfe consistency and verifying not already installed...
all files already exist and are up to date.

. net install ftools, from("https://raw.githubusercontent.com/sergiocorreia/ftools/master/src/")
checking ftools consistency and verifying not already installed...
all files already exist and are up to date.

. which reghdfe
D:\Dropbox\ado15\plus\r\reghdfe.ado
*! version 5.6.8 03mar2018

. version
version 15.1
```

**Comment by simonheb** [comment]
turns out, this is really easy to solve if you actually follow the instructions given by @sergiocorreia.

if anyone lands here because they ran into the same issue, just run:
```
reghdfe, compile
ftools, compile
```

**Comment by sergiocorreia** [comment]
Interesting. Thanks for the report, and for the solution. Even though I suggest the compile steps, I thought I had found a way to avoid it, but probably forgot to check other ado files besides the main reghdfe.

**Comment by Rachel-Xu115** [comment]
hello! When I use the command gtfp, i come to the same problem(  _ddf():  3021  class compiled at different times), but when I type the same line "gtfpch, compile", Stata warns the error "invalid syntax" .

**Comment by sergiocorreia** [comment]
You probably want to discuss this with the `gtfpch` authors. Also, compilation errors should mostly be a thing of the past for reghdfe as I ended up finding that loading a compiled file took more time than just including the mata code directly and letting Stata handle it.
