### ISSUE TITLE
Possible bug: "VCE options not supported" for documented bw(#)

### ISSUE THREAD

**Issue by jeffgortmaker** [sergiocorreia/reghdfe#166]
Hi and thanks for all the great work on this package!

I recently updated my `reghdfe` version and started getting error messages about unsupported `vce` options that used to work in the old version (and that still work in `ivreg2`).

I don't remember what version I was on previously -- maybe the `vce` syntax has changed?

Example code:

```
capture ado uninstall ranktest
capture ado uninstall ivreg2
capture ado uninstall ftools
capture ado uninstall reghdfe

ssc install ranktest
ssc install ivreg2
net install ftools, from("https://raw.githubusercontent.com/sergiocorreia/ftools/master/src/")
net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")

ftools, compile
reghdfe, compile

version
ivreg2, version
reghdfe, version

sysuse tsline2
tsset day
ivreg2 calories ucalories, bw(3)
reghdfe calories ucalories, noconstant vce(, bw(3))
```

Output:

```
. ssc install ranktest
checking ranktest consistency and verifying not already installed...
installing into ../../packages\...
installation complete.

. ssc install ivreg2
checking ivreg2 consistency and verifying not already installed...
installing into ../../packages\...
installation complete.

. net install ftools, from("https://raw.githubusercontent.com/sergiocorreia/ftools/master/src/")
checking ftools consistency and verifying not already installed...
installing into ../../packages\...
installation complete.

. net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")
checking reghdfe consistency and verifying not already installed...
installing into ../../packages\...
installation complete.

. 
. ftools, compile
(compiling lftools.mlib for Stata 15.1)
(library saved in ../../packages/l/lftools.mlib)

. reghdfe, compile
(compiling lreghdfe.mlib for Stata 15.1)
(library saved in ../../packages/l/lreghdfe.mlib)

. 
. version
version 15.1

. ivreg2, version
04.1.10

. reghdfe, version
../../packages\r\reghdfe.ado
*! version 5.6.9 03mar2019

Required packages installed?
- ftools            yes

. 
. sysuse tsline2

. tsset day
        time variable:  day, 01jan2002 to 31dec2002
                delta:  1 day

. ivreg2 calories ucalories, bw(3)

OLS estimation
--------------

Estimates efficient for homoskedasticity only
Statistics robust to autocorrelation
  kernel=Bartlett; bandwidth=3
  time variable (t):  day

                                                      Number of obs =      365
                                                      F(  1,   363) =        .
                                                      Prob > F      =        .
Total (centered) SS     =  3046082.289                Centered R2   =   1.0000
Total (uncentered) SS   =   4790725974                Uncentered R2 =   1.0000
Residual SS             =  1.44388e-19                Root MSE      =  2.0e-11

------------------------------------------------------------------------------
    calories |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
   ucalories |          1   1.40e-14  7.2e+13   0.000            1           1
       _cons |       -100   5.19e-11 -1.9e+12   0.000         -100        -100
------------------------------------------------------------------------------
Warning: estimated covariance matrix of moment conditions not of full rank.
         overidentification statistic not reported, and standard errors and
         model tests should be interpreted with caution.
Possible causes:
         covariance matrix of moment conditions not positive definite
         covariance matrix uses too many lags
         singleton dummy variable (dummy with one 1 and N-1 0s or vice versa)
partial option may address problem.
------------------------------------------------------------------------------
Included instruments: ucalories
------------------------------------------------------------------------------

. reghdfe calories ucalories, noconstant vce(, bw(3))
VCE options not supported: bw(3)
```

**Comment by sergiocorreia** [comment]
You are right. The bw() and related options actually used ivreg2 to do the calculations. But recent versions of reghdfe don't use ivreg2 anymore (too complex) and that functionality was moved to ivreghdfe, which is just a modification of ivreg2 that supports absorb().

In summary: What you want to use is ivreghdfe

**Comment by jeffgortmaker** [comment]
Got it, thanks.

**Comment by Danferno** [comment]
Just wanted to mention I had the same issue and switching to ivreghdfe fixed it.

**Comment by Danferno** [comment]
Nvm, it worked on small samples, but when I try it with very large data, I get following error:
               m_omega():  3301  subscript invalid
               s_omega():     -  function returned error
                 <istmt>:     -  function returned error
Is this in the reghdfe part, or is this an issue with ivreg2?

**Comment by sergiocorreia** [comment]
The `*_omega()` functions are part of ivreg2. If you run this with ivreg2 directly (without fixed effects) do you also get an error? (I would suspect so, because "subscript invalid" is more likely of a bug in omega than on an input error)

**Comment by Danferno** [comment]
Strangely, I was able to run the ivreg2 regression but not the ivreghdfe version. Below, I've attached a screenshot that shows the output of ivreg2 and then that of ivreghdfe. I've also attached the code I used.

```
ivreg2 D_`price'_down_h`h' L_x_`price' FF4_alt1_norm c.L_x_`price'#c.FF4_alt1_norm, cluster(month id_nr_unique) bw(4)
ivreghdfe D_`price'_down_h`h' L_x_`price' FF4_alt1_norm c.L_x_`price'#c.FF4_alt1_norm, absorb(id_nr_unique month12) cluster(month id_nr_unique) bw(4)
```
![temp](https://user-images.githubusercontent.com/20988490/54215190-ced96a80-44e7-11e9-8656-c1485c77f23f.png)

**Comment by finjay** [comment]
Hello,
I also ran into some problem using vce(robust, bw(2)) with reghdfe and tried using it with ivreghdfe as suggested previously and I am getting that VCE options not supported: bw(2).
Is this no longer available even with old?  Would there be a way to install an older version again? 
Thank you.

**Comment by finjay** [comment]
I have found that the problem I had was with  using absorb with vce(robus, bw(2) ) in reghdfe.
This used to work previously but it seems to cause a problem in the new version.

**Comment by sergiocorreia** [comment]
Yes, the extra VCE options (that are part of ivreg2) were moved to ivreghdfe and are not accessible anymore (for very practical reasons, b/c ivreghdfe is just a wrapper to ivreg2).

You can either use ivreghdfe as you used reghdfe, or use the oooooold version of reghdfe (`reghdfe y x, a(..) vce(..) version(3)`)
