### ISSUE TITLE
Issue with ms_add_comma

### ISSUE THREAD

**Issue by CMS27** [sergiocorreia/reghdfe#168]
Hello Sergio,

First of all, thank for the great work with this package.

Updating both reghdfe and ftools I end up with a systematic error message when using reghdfe:
"command ms_add_comma is unrecognized". 

I tried to fix it by installing directly  the latest version of your ftools/src/ files but then I get another error: "Class FixedEffect is unrecognized"

So it seems I can't use reghdfe anymore right now. Do you have any idea of what goes wrong ? 

Thank a lot in advance,
Best,
Clément

**Comment by shizhengzheng** [comment]
I also encounter the error:  “unrecognized command ms_add_comma” when running command reghdfe.

**Comment by sergiocorreia** [comment]
The ms_add_comma problem is an SSC but; already reported it.

The other bug I'm not sure, but might be fixed if you run ftools,compile  , reghdfe,compile , and restart Stata

**Comment by CMS27** [comment]
Great, thx a lot.
So I'm just waiting for Stata to fix the SSC bug.
Best,
Clément

**Comment by sergiocorreia** [comment]
Opened for visibility until fixed on SSC.

**Comment by egg16** [comment]
Sergio,

Thanks for your hard work on this front. I am commenting to cement my place for information on this bug. I also have encountered the ms_add_comma unrecognized problem. 

Thanks

**Comment by sergiocorreia** [comment]
The missing file has been fixed, and installing from SSC should work now.

**Comment by shizhengzheng** [comment]
> The missing file has been fixed, and installing from SSC should work now.

Hi Sergio,

The error message：“unrecognized command:  ms_add_comma” is still there when I run reghdfe.

**Comment by sergiocorreia** [comment]
Did you uninstall/reinstall?

**Comment by dulal1986** [comment]
Works after uninstalling/reinstalling.

**Comment by shizhengzheng** [comment]
> Did you uninstall/reinstall?

I did but nothing changed. 

{. ssc install reghdfe
checking reghdfe consistency and verifying not already installed...
installing into c:\ado\plus\...
installation complete.

. reghdfe cedu fedu medu,absorb(rep78)
unrecognized command:  ms_add_comma
r(199);}

**Comment by sergiocorreia** [comment]
I think you need to uninstall first, before trying ssc

**Comment by shizhengzheng** [comment]
> I think you need to uninstall first, before trying ssc

Yes I did it before installing. 
. ado uninstall reghdfe
package reghdfe from http://fmwww.bc.edu/repec/bocode/r
      'REGHDFE': module to perform linear or instrumental-variable regression absorbing any number of high-dimensional fixed effec
> ts
(package uninstalled)

I am from China so I guess there maybe some problems with regard to network.

**Comment by sergiocorreia** [comment]
Sorry for not being clear: the file is actually missing on ftools, so the package that needs to be reinstalled is ftools.

Best,
S

**Comment by shizhengzheng** [comment]
> Sorry for not being clear: the file is actually missing on ftools, so the package that needs to be reinstalled is ftools.
> 
> Best,
> S

Great！It works. Thank you so much！
