### ISSUE TITLE
Saving standard errors and covariance matrix of the fixed effects

### ISSUE THREAD

**Issue by giorgiaestefani** [sergiocorreia/reghdfe#170]
Hi, 

I am using reghdfe with many fe (areas_years):
reghdfe y x, absorb(fe_areas_years=d_areas_years) vce(cluster areas)

I need to save the estimated coefficients of the fixed effects (and that's easy), the s.e. and the covariance matrix of the estimated fixed effects. The best would be to have them in a .dta file (similarly as absorb(fe_areas_years=d_areas_years) does for the estimated coefficients on the fixed effects).

I could not find out how to do (I already tried with Statalist). 

Many thanks for your time. Best,

Giorgia

**Comment by sergiocorreia** [comment]
I just realized I replied to your email before seeing your Github issue. As explained there, saving SEs is not currently supported by reghdfe (and might actually be a bad idea).
