### ISSUE TITLE
Question about using margins with reghdfe

### ISSUE THREAD

**Issue by adamlauretig** [sergiocorreia/reghdfe#173]
Hi, 

Thanks for the awesome package!

I had a question about using margins for conditional effect estimation:
Does margins use the fixed effects in estimating conditional effects?

Thank you!

**Comment by sergiocorreia** [comment]
Hi Adam,

I remember researching that when writing the margins support, but honestly can't rememer now (I'm on paternity leave, so no free time to check out).

I recall I tried to do the same things xtreg/areg did, so perhaps you could compare against what they do?

-Sergi

**Comment by adamlauretig** [comment]
Sergio,

Gotcha, thanks, I'll check them out. And congratulations on fatherhood!

Adam
