### ISSUE TITLE
reghdfe requires ftools version 2.34.0

### ISSUE THREAD

**Issue by mathkaren** [sergiocorreia/reghdfe#175]
Hi Sergio,

I'm trying to use reghdfe, but I got an error message saying "you are using version 2.30..3 of ftools, but require version 2.34.0." I looked up at github, only finding the lastest version of ftools is 2.31.3 06jan2019. Could you share how to update ftools to the required version 2.34.0?

Many thanks!

Best,
Karen

**Comment by sergiocorreia** [comment]
Hi Karen,

The readme file was not updated, but the latest version on github is 2.36:

https://github.com/sergiocorreia/ftools/blob/master/src/ftools.ado#L1

**Comment by mathkaren** [comment]
Thank you Sergio, for such a quick response. 

The Stata I worked is in a secure environment, where the internet connection is controlled by the IT department and all the package installation and upgrade have to be done manually by them through tickets. For this upgrade, should I just ask them to uninstall and reinstall from github (not ssc)?

Thank you!

Best,
Karen

**Comment by sergiocorreia** [comment]
That's an option. Alternatively, can you just download the repo as a zip file and extract it in your user ado folder?

**Comment by mathkaren** [comment]
Thanks for the suggestion. I guess I cannot use the alternative method: the data environment is like a vault, I cannot download to or move things to the environment. Maybe I will just direct the IT department to the GitHub repo and let them them choose between the two options.

Thank you for the help!

**Comment by yorktien** [comment]
you can try `ssc install reghdfe, replace` it worked for me prefectly. 

If you still encounter problems, like ftools problem, try `ssc install ftools, replace` . It will work just fine.
