### ISSUE TITLE
class FixedEffects undefined error with newest version of -reghdfe-

### ISSUE THREAD

**Issue by fburlig** [sergiocorreia/reghdfe#181]
Hi,
I have the newest version of -reghdfe-, but I'm getting a `r(3000): class FixedEffects undefined` error when I try to run anything. I'm on a Mac with Stata 15.1. 

MWE below:
`sysuse auto`

`reghdfe price, abs(foreign)`
I get the same error with
`reghdfe price, noabs`
but
`areg price, abs(foreign)`
works just fine. Happy to provide any other info that would be useful!

**Comment by sergiocorreia** [comment]
Hi Fiona,

- do you have the latest ssc ir github version?
- can you try "reghdfe, compile" to see if the issue gets fixed?


Best
S

**Comment by fburlig** [comment]
Hey,
`reghdfe, compile` worked perfectly - thank you! ...and now that you've replied, I see the note in the latest updates about doing this. Sorry for not reading closely. I only have the latest ssc version, not the GitHub version.
