### ISSUE TITLE
reghdfe not working on STATA 14

### ISSUE THREAD

**Issue by SantiFilippo** [sergiocorreia/reghdfe#190]
I am using reghdfe in STATA 14. My regression takes the form of 
`	
reghdfe ln_flow_domestic_od ln_l1_num_proj_concl_d `controls', absorb(pair o_time) vce(cluster destination)
`
 but it keeps returning the following message:
`class FixedEffects undefined
r(3000);
`
I tryed to run my regression on STATA 15 and this problem did not arise. Curiously, I am able to run ppmlhdfe (same code as above) on my STATA 14. Any Idea for why is this happening? Is reghdfe incompatible with STATA 14?

**Comment by sergiocorreia** [comment]
Can you try "reghdfe,compile"? This is due to a leftover problem from the
SSC version of reghdfe.

**Comment by SantiFilippo** [comment]
It worked. Thank you very much!
