### ISSUE TITLE
"unrecognized command:  _ms_findomitted" Error

### ISSUE THREAD

**Issue by EroyMada** [sergiocorreia/reghdfe#191]
I am running Stata/SE 11.2 and recently re-installed reghdfe after a necessary hard drive swap on my PC. Now, when I run a very simple version of the code, 

reghdfe Y X1 X2, absorb(firmvar industry_year)

I get the following log output / error:

(dropped 3503 singleton observations)
(MWFE estimator converged in 122 iterations)
unrecognized command:  _ms_findomitted
r(199);
end of do-file
r(199);

I have been grateful to extensively use this package for several years now without any issue. However, this version is not working for me. It appears that the package is properly installed and all of the dependent files are also installed.

. reghdfe, version
c:\ado\plus\r\reghdfe.ado
*! version 5.7.2 29jul2019

Required packages installed?
- ftools            yes
- boottest          yes

Please help! :)

**Comment by sergiocorreia** [comment]
It seems that the missing command was only added in v13 or v12.

As an alternative, can you run reghdfe with the "old" option, which will call version 3 of reghdfe (instead of version 5). That version should be compatible with Stata 11.2

**Comment by EroyMada** [comment]
That worked! Thank you very much for the prompt reply!
