### ISSUE TITLE
RDD with different slopes for each cutoff

### ISSUE THREAD

**Issue by adamaltmejd** [sergiocorreia/reghdfe#193]
Hello! Thanks for an amazing package - saved so many hours of computing time!

I'm working on a project where we are running local polynomial RD estimation with many cutoffs and want to include cutoff fixed effects. The dataset has N~500k with 50k cutoffs.

When allowing for variable slopes the solver gets much slower. I was trying to follow the instructions for in what order to specify the fixed effects but not sure I'm getting it right. Mainly, the problem is that to allow for different slopes above and below the cutoff I need to include an indicator for `above_cutoff` - but this is also the exogenous variable of interest - so I cannot use fixed effects at the `id_cutoff#above_cutoff` level. Instead, I have to run:

`absorb(id_cutoff##c.cutoff_distance id_cutoff#above_cutoff#c.cutoff_distance)`

which is really slow. 

Not to speak of the 2-nd degree polynomial. What I'm doing currently is, and for this specification I haven't even gotten the solver to converge. What is the most efficient way to specify this model?

```
absorb(
    id_cutoff##c.cutoff_distance 
    id_cutoff#above_cutoff#c.cutoff_distance
    id_cutoff##c.cd_squared
    id_cutoff#above_cutoff#c.cd_squared
)
```

**Comment by sergiocorreia** [comment]
I think the problem is in the `#c.` elements of absorb. They make results MUCH slower so I often prefer to use `##.c.` even if its redundant. Although in your case it seems you can't do that because you have above cutoff as the regressor of interest?

Besides the slowness of `#.c`, it should be be better to do:

```
absorb(
    id_cutoff##c.(cutoff_distance cd_squared)
    id_cutoff#above_cutoff#c.(cutoff_distance cd_squared)
)
```

By the way, I'm curious about your RD specification. Do you use weights (epa/triangular?) or any of the automatic bandwidth selection from e.g. Imbens or Cattaneo et al?

**Comment by adamaltmejd** [comment]
Thanks! Will try. In this version, I use a pre-calculated bandwidth and no weights nor any additional controls. So the full command is something like:

```
reghdfe y 1.above_cutoff if abs(cutoff_distance) < bw, absorb(...)
```

Would also want to run this as a fuzzy RD but I guess that is not exactly gonna go faster. Was thinking about an alternative approach. What do you think of running the full specification (`absorb(id_cutoff##above_cutoff#c.cutoff_distance)`), saving the fixed effects and then subtracting only the part that I want from `y` and running the `above_cutoff` regression on this residualized version? Could that be faster?

**Comment by sergiocorreia** [comment]
> Was thinking about an alternative approach. What do you think of running the full specification (absorb(id_cutoff##above_cutoff#c.cutoff_distance)), saving the fixed effects and then subtracting only the part that I want from y and running the above_cutoff regression on this residualized version? Could that be faster?

That might work, although the problem is you won't get the SEs.
