### ISSUE TITLE
Default weight option

### ISSUE THREAD

**Issue by matthieugomez** [sergiocorreia/reghdfe#20]
reghdfe defaults to fweight, while reg/areg defaults to aweight. Unless there's a reason I'm missing, it'd be nice if they had the same defaults, 
Out of curiosity, why does fweight tend to return a "numerical overflow" error (in areg or reghdfe)?

**Comment by sergiocorreia** [comment]
Makes sense. I was not even aware I was allowing default weights. Pushing patch now.

**Comment by sergiocorreia** [comment]
About the overflow issue, do you have an example? I haven't been using weights at all in my regressions since the last update so I'm not aware of the corner cases..

**Comment by matthieugomez** [comment]
It actually happens even with _regress, so it has nothing to do with fixed effects

From the doc:
0. numerical overflow
You have attempted something that, in the midst of the necessary calculations, has resulted in something too large for Stata to deal with accurately. Most commonly, this is an attempt to estimate a model (say, with regress) with more than 2,147,483,647 effective observations. This effective number could be reached with far fewer observations if you were running a frequency-weighted model.

**Comment by sergiocorreia** [comment]
Indeed, it seems the culprit is _regress. I traced a quick example and it failed here:

```stata
_regress y x [fweight=obs]
```

As long as the effective number of obs. reaches the maximum precision of -double- (2.17bn obs), the regression fails. Also note that Stata 14 apparently lifted this limit.
