### ISSUE TITLE
Issue 3498 assertion is false in store_alphas()

### ISSUE THREAD

**Issue by sammygyoung** [sergiocorreia/reghdfe#204]
Hello,

When I run the following code on about 85 million observations

```
reghdfe lnearnings refage* i.year, absorb(personID firm_overall = firmID) groupvar(mobility_group) verbose(2) pool(11) compact nosample
```

I get the following error
```
## Storing estimated fixed effects 

   - Loading d = e(depvar) - xb - e(resid)
                assert():  3498  assertion is false
FixedEffects::store_alphas():     -  function returned error
                 <istmt>:     -  function returned error
r(3498);

end of do-file
r(3498);

end of do-file

r(3498);

```

Any suggestion on what might be going on here would be greatly appreciated, thanks! 

**System info:**
- Stata version: 16.1 
- OS: Windows 10
- reghdfe version: 5.8.0 27dec2019

**Comment by sammygyoung** [comment]
I resolved the issue by getting rid of nosample. I am guessing that this cannot be combined with saving the FEs.

**Comment by dzqdudley** [comment]
> I resolved the issue by getting rid of nosample. I am guessing that this cannot be combined with saving the FEs.

Hi, I ran into this issue as well. Could you explain how you got rid of nosample? Did it mean dropping the samples you would not use for this regression? Thanks a lot!
