### ISSUE TITLE
Assert_msg Error

### ISSUE THREAD

**Issue by achenzion** [sergiocorreia/reghdfe#21]
reghdfe/package/reghdfe.ado

Line 2544 assert_msg ...

has the incorrect syntax and thus throws an error when using usecache. I would have tried to fix it, but am unsure which assert you want to use. For future reference, how are you choosing Assert or assert_msg?

**Comment by sergiocorreia** [comment]
Hi Ayal,

Assert is a Stata command while assert_msg() is a Mata function. Both are similar in that they wrap, respectively, the Stata command -assert- and the Mata function -assert()-, while giving an explanatory message.

A few questions:
- What version of reghdfe is that? (you can find it with "reghdfe, version")
- What command did you run?
- More useful than that is showing an example of the error with the standard data set ("sysuse auto") so I can test it on my end.

Best,
Sergio

**Comment by achenzion** [comment]
Hello Sergio,

See below for the code I ran and the result. It looks like I was using 3.0.45 (I have been trying to stay up-to-date). Unfortunately I was not able to find a packaged dataset that replicates my problem, but I tried to rename the variables in a way that clarifies the issues involved.

In my framework there is a unique ID1xID2 observation, but my identification is coming from comparing two such observations within the same CL

>Note: CLxID1=group(CL ID1)

I hope this is helpful. I found that if I changed 
```
assert_msg ....
```
 to 
```
Assert ...
``` 
The issue went away, but I am unsure if that was appropriate.

Code and Output
--------------------------

``` 
reghdfe, version
```
>3.0.45 02jun2015
>
>Dependencies installed?
>- ivreg2            not
>- avar              not
>- tuples            not

```
reghdfe Y X, absorb(CLxID1 ID2)  vce(cluster CL)
```
>(dropped 63 singleton observations)
>(converged in 3 iterations)
>
>
>HDFE Linear regression                            Number of obs   =   19071899
>Absorbing 2 HDFE groups                           F(   1,   1599) =      33.95
>Statistics robust to heteroskedasticity           Prob > F        =     0.0000
>                                                  R-squared       =     0.3272
>                                                  Adj R-squared   =     0.3142
>                                                  Within R-sq.    =     0.0000
>Number of clusters (CL)      =       1600         Root MSE        =     0.0205
>                                  (Std. Err. adjusted for 1600 clusters in CL)
>
>-
>             |               Robust
>           Y |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
>           X |    .000802   .0001377     5.83   0.000      .000532     .001072
>
>Absorbed degrees of freedom:
>
>-
> Absorbed FE |  Num. Coefs.  |=   Categories  | -   Redundant     | 
>-------------|----------------|-----------------|----------------|
>      CLxID1 |            0        |  334011    |     334011 *   | 
>         ID2 |            0    |       25852   |       25852 *   | 
>* = fixed effect nested within cluster; treated as redundant for DoF computation



```
 reghdfe Y X, absorb(CLxID1 ID2)  vce(cluster CL) savecache
```
>(dropped 63 singleton observations)
>(converged in 3 iterations)

```
reghdfe Y X, absorb(CLxID1 ID2) vce(cluster CL) usecache
```
>unrecognized command:  assert_msg

**Comment by sergiocorreia** [comment]
Got it! Thanks for the detailed explanation. 

As you said, replacing "assert_msg" fixed the problem. Oddly, I never had trouble with it because I have a custom "assert_msg" [command](https://github.com/sergiocorreia/stata-misc/blob/master/assert_msg.ado).

I'm updating it right now on 3.0.48 .

Cheers,
Sergio

PS: You are probably aware of it, but if you feel like saving coding time you can always avoid the "egen group" line and just type cl#id1 directly into absorb() or even vce(cluster ..)
