### ISSUE TITLE
[Results in eClass missing?] 

### ISSUE THREAD

**Issue by leonschmidt93** [sergiocorreia/reghdfe#214]
Hej Sergio,

Thank you very much for reghdfe, it´s a great program and I am using it a lot!

However, I am puzzled by one point. I don´t know if it is a bug or if I am doing something wrong. When using xtreg , fe, this command will give me the number of groups for which the fixed effects are included (e.g. the number of firms for firm-level regressions). From the help file of reghdfe I figure that the scalar e(K#) should report the similar statistic. However, when I type "ereturn list" after the regression the scalars e(K1) or generally e(K#) aren´t reported. Am I doing something wrong here? 

I am using the latest version on SSC and Stata 16.1 

Thank you very much for your help!

All the best
Leon

**Comment by sergiocorreia** [comment]
You are right that that's not being reported, need to update the help file. Those values are now in the e(dof_table) object, which you can access through e.g.

```stata
matrix a = e(dof_table)
matrix list a
```

That said, I guess you want this to add a row to the regression table. If you are using estout, this is what I do in those cases:

```stata
* Suppose I want to report number of cities, counties, and states in a regression. Then:

	* # Cities
	qui gdistinct city_id if e(sample)
	qui estadd local NCity =`r(ndistinct)'

	* # Counties
	qui gdistinct gisjoin1880 if e(sample)
	qui estadd local NCounty =`r(ndistinct)'
	
	* # States
	qui gdistinct state_id if e(sample)
	qui estadd local NState =`r(ndistinct)'


esttab * ... , ... stats(N NCity NCounty NState)
```

Here, gdistinct command is from gtools package (but you can just install the `distinct` command which works the same but slower. And `estadd` is from the `estout` package (see [help](http://repec.org/bocode/e/estout/estadd.html)).

Best,
S

**Comment by leonschmidt93** [comment]
Thank you very much Sergio! This worked perfectly. And yes, I was looking for a solution in Latex and this worked.
