### ISSUE TITLE
[BUG] cannot compile reghdfe when installing new versions

### ISSUE THREAD

**Issue by yian-yin** [sergiocorreia/reghdfe#234]
- Stata version: Stata 14.2 Jan 2018
- OS: Mac OS 10.15

**Behavior**

I was trying to install the new version (6.12) of reghdfe and could not compile it

. reghdfe, compile
last estimates not found
r(301);

The same problem does not occur for v5.9

**Comment by sergiocorreia** [comment]
Sorry, as of version `version 5.7.0 20mar2019` you don't need to compile reghdfe anymore to use it. I noticed I updated this on the help file and on part of the readme, but it's still at the bottom on the readme, so will update it.

Plz reopen if you run into errors due to lack of compile option.
