### ISSUE TITLE
-- predict, stdp -- 

### ISSUE THREAD

**Issue by PMitchDowney** [sergiocorreia/reghdfe#26]
Hello,

I'm glad that the predict command can be used after reghdfe (if the fixed effects are saved), but I don't think it's possible to get the standard error of the prediction (I get the error: "option stdp not allowed"). It would be nice if -- predict, stdp --  could be used to get the standard error of the X'B prediction (ignoring uncertainty in the estimated fixed effect), similar to how it works after areg (I believe). 

Thanks!
-Mitch

**Comment by sergiocorreia** [comment]
You are right, will check how `areg` does it.

Best,
-S
