### ISSUE TITLE
[BUG] Version 6.12.3 of reghdfe appears to break ppmlhdfe

### ISSUE THREAD

**Issue by mmooddaa** [sergiocorreia/reghdfe#273]
Version 6.12.3 of `reghdfe` appears to have broken `ppmlhdfe`. After updating `reghdfe` to 6.12.3, I get the following error when running `ppmlhdfe`:

```stata
cap ado uninstall ftools
cap ado uninstall reghdfe
cap ado uninstall ppmlhdfe

ssc install ftools
ssc install reghdfe
ssc install ppmlhdfe

. ppmlhdfe price weight, a(turn)
ppmlhdfe requires the reghdfe package (version 6 or newer), which is not installed
    - install from SSC
    - install from Github
(error occurred while loading ppmlhdfe.ado)
r(9);
```

`ppmlhdfe` stoped giving me this error after I reinstalled version 6.12.1 of `reghdfe`.

I am using the following version of Stata:
- Stata version: Stata 17.0 21aug2023
- OS: MacOS 13.4

Apologies if I should have posted this bug report in `ppmlhdfe` instead.

**Comment by sergiocorreia** [comment]
Hi Michael,

I traced the bug to a missing file on the SSC version of reghdfe. In particular, the file `reghdfe5.mata` is missing from SSC. As a temporary workaround, if you install reghdfe from Github the problem dissapears:

```
net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/")
```

**Comment by mmooddaa** [comment]
Great, that works. Thanks!
