### ISSUE TITLE
[BUG] error occurred while loading reghdfe.ado

### ISSUE THREAD

**Issue by hangochen** [sergiocorreia/reghdfe#274]
# Before submitting the bug report

1. Verify that you are using the latest versions of reghdfe and ftools (`which reghdfe`). Note that the latest version is usually on Github and not on SSC.
*! version 6.12.3 08aug2023

2. Verify that your Stata is updated (`update query`).

# Bug report

**Please complete the following information:**

- Stata version: Stata 17.0 Jul 2023
- OS: Windows 10

**Behavior**

- Expected behavior: use reghdfe to run a regression with fixed effects and clustering. 
- Actual behavior:

```stata
. clear

. use http://fmwww.bc.edu/ec-p/data/wooldridge/jtrain

. reghdfe lwage expersq union married, absorb(year) vce(cluster fcode)
function cleanup_before_saving() not declared in class Factor
(57 lines skipped)
(error occurred while loading reghdfe.ado)
r(3000);

```

**Steps to reproduce the problem**

See above.

**Comment by sergiocorreia** [comment]
Hi hangochen,

I suspect ftools is not in updated. Can you run:

```
which reghdfe
which ftools
```

What I get on my end after these commands is:

```

. which reghdfe
c:\ado\plus\r\reghdfe.ado
*! version 6.12.3 08aug2023

. 
. which ftools
c:\ado\plus\f\ftools.ado
*! version 2.49.1 08aug2023
```

**Comment by hangochen** [comment]
Thanks Sergio, for your quick response! 
I see. Yes, the error no longer persists after I updated ftools.
