### ISSUE TITLE
[BUG] Missing `strok` option with `nopartialout` and `varlist_is_touse`

### ISSUE THREAD

**Issue by mcaceresb** [sergiocorreia/reghdfe#276]
# Bug report

I believe this is the cause of sergiocorreia/ivreghdfe/issues/36. The fix is to add `strok` to [line 263 of `reghdfe.ado`](https://github.com/sergiocorreia/reghdfe/blob/master/current-code/reghdfe.ado#L263)

- Stata version: 14.1
- OS: Arch Linux Kernel 6.4.9-arch1-1

**Behavior**

- Expected behavior: Allow cluster variable to be string.
- Actual behavior: touse variable is set to all 0s if cluster variable is string

```stata
. clear
. qui set obs 10
. gen byte touse = 1
. gen a = _n
. gen b = string(_n)
. reghdfe touse, cluster(a) nopartialout varlist_is_touse
. reghdfe touse, cluster(b) nopartialout varlist_is_touse
(dropped 0 singleton observations)
insufficient observations
r(2001);
```

**Steps to reproduce the problem**

See MWE above.

**Comment by sergiocorreia** [comment]
Fixed, thanks!
