### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JanDitzen** [sergiocorreia/reghdfe#277]
I wrote on the Stata list but I am opening up a report here as well.

I recently update reghdfe to the august 2023 version (6.12) from SSC. When I try to use reghdfe the following error occurs:

```
function cleanup_before_saving() not declared in class Factor
```

The error occurs on Stata 17 and 18. I also removed (by hand) mata libraries of former versions and checked for any remains of old versions, but the error persists.

**Comment by sergiocorreia** [comment]
Hi Jan,

Can you try upgrading your version of `ftools` as well? 

Thanks!
S

**Comment by JanDitzen** [comment]
That works, thanks a lot!
