### ISSUE TITLE
-estfe- doesn't detect fixed effects of -xtreg, fe- and other xt-class commands

### ISSUE THREAD

**Issue by NilsEnevoldsen** [sergiocorreia/reghdfe#29]
`estfe` doesn't detect fixed effects of `xtreg, fe` and other xt-class commands.

Might be outside its scope. Your call. :smiley:

**Comment by sergiocorreia** [comment]
It seems `xtreg, fe` stores the fixed effect in `e(ivar)`.
However, we would need to check for `e(model)=="fe"`.

Would that be enough for the other xt* models? I don't really use them often.

**Comment by NilsEnevoldsen** [comment]
Yeah, `xtivreg` does the same.
