### ISSUE TITLE
Parsing syntax for weights in hdfe

### ISSUE THREAD

**Issue by matthieugomez** [sergiocorreia/reghdfe#34]
`hdfe` returns an error when using weights (both on SSC and in the master branch)

```
. sysuse nlsw88.dta, clear
. hdfe wage [w=tenure], a(fe) gen(new)
weights not allowed
```

The error is returned by the following call to ParseIV
```
 . ParseIV wage [fweighttenure], estimator() ivsuite()
```

**Comment by sergiocorreia** [comment]
Fixed.. small but annoying parsing bug
