### ISSUE TITLE
reghdfe crashes after -fvset-

### ISSUE THREAD

**Issue by sergiocorreia** [sergiocorreia/reghdfe#35]
``` stata
sysuse auto
fvset base 1 foreign
reghdfe price weight, a(foreign)
```

Problem lies when parsing the (ParseAbsvars.ado). Syntax doesn't expand to "i.foreign" but to "ib1.foreign".

A solution would be to replace -syntax- completely (including when parsing indep. vars) which would fix several related bugs but would involve a lot of work.

**Comment by markeschaffer** [comment]
When updating ivreg2 to handle factor variables, I found it useful to write a subroutine that stripped out the FV b, n and o operators. Applied to a varlist, it returns the varlist with minimal FV varnames.  Applying it to your expanded varlists could perhaps solve your problem.

Here's how it works.  For example,

fvexpand i.foreign =>
r(varlist) : "0b.foreign 1.foreign"

fvstrip i.foreign, expand =>
r(varlist) : "0.foreign 1.foreign"

fvstrip i.foreign, expand dropomit =>
r(varlist) : "1.foreign"

It lives inside ivreg2 (as "ivreg2_fvstrip") if you want to have a look.

**Comment by sergiocorreia** [comment]
This seems *exactly* like what I need!

In fact, it also closes another bug, thanks to the -dropomit- option: https://github.com/sergiocorreia/reghdfe/issues/22

Can I copy-paste it to reghdfe?

Thanks!
S

**Comment by markeschaffer** [comment]
Sure, no problem.

Do you think it might be of general use?  I hesitated about putting it on SSC because that brings with it the responsibility of maintaining it, either the syntax gets frozen or it breaks when users update, etc.

Maybe a Statalist thread with the code so that anyone who wants can use it freely, modify as they see fit, and with no responsibility for me to maintain it?

**Comment by sergiocorreia** [comment]
Sounds like a good idea; also maybe on Github at some point..

**Comment by randomgambit** [comment]
NOW I understand why reghdfe didnt work on my monthly dummies after I fvset them at some point. ;-)

**Comment by palapid** [comment]
Is `fvset clear <varlist>` before running `reghdfe` the main workaround for this bug at this time? Just discovered this thread after figuring this out!

**Comment by sergiocorreia** [comment]
Indeed.

(The version sitting on my computer avoids that problem altogether but it won't be out for at least a week)

**Comment by sergiocorreia** [comment]
Works on dev version thanks to Mark's fixes; closed
