### ISSUE TITLE
Reghdfe can't save stage(reduced ols first) regressions

### ISSUE THREAD

**Issue by chenfeilu** [sergiocorreia/reghdfe#39]
Hi,

Thanks for making reghdfe! This command is amazing! I'm having trouble using reghdfe to output multiple forms of the regression. For example, when I run 

reghdfe price (mpg = rep78), absorb(foreign) stages(first reduced ols)

I see all four regressions displayed. I would like to save all of these estimates, but I can't.

I am able to use 

```
estimates replay reghdfe_first1
```

to show the first stage regression, but whenever I try to use eststo or estimates store to save it, it shows me the IV coefficients.

For example,

```
eststo reghdfe_first1
esttab reghdfe_first1
```

Shows me the IV output, not the first stage. Do you know how to save the output for all of the four regressions, particularly for use in estout/esttab?

**Comment by sergiocorreia** [comment]
Sorry for the late reply.

The reason is that `estimates replay` only shows the table but does not set those estimtes as the "active" ones. For that, you need the `estimates restore` command:

```stata
. estimates restore reghdfe_first1
(results reghdfe_first1 are active now)



. esttab

----------------------------
                      (1)   
                      mpg   
----------------------------
rep78               1.219   
                   (1.54)   
----------------------------
N                      69   
----------------------------
t statistics in parentheses
* p<0.05, ** p<0.01, *** p<0.001

```

Thus, the restore subcommand allows you to then call estout as you need.

Best,
S

**Comment by pfagandi** [comment]
Hello!

Can I recover the other regressions (OLS and reduced) too?

I know how to call the first stage, and that if I save the estimates after running the regressions I got the second ones, but I don't guess how to get the OLS and reduced ones.

Thank you!

Paulo

**Comment by sergiocorreia** [comment]
Hi Paulo,

That feature is moved to [`ivreghdfe`)[https://github.com/sergiocorreia/ivreghdfe/], where you can use the exact same syntax as in ivreg2 (`help ivreg2`). Now, ivreg2 allows to get the reduced ones but not the OLS, so for that you would just need to do a normal ols call.

Best,
Sergio

**Comment by pfagandi** [comment]
Thank you, indeed using ivreghdfe allos to get the red form with rf saverf as with ivreg2.

Best!

Paulo

**Comment by pfagandi** [comment]
Hello, I have one more question if someone can help.

I have been trying to figure it out if ivreghdfe absorbs the fixed effects also for the first stage and reduce form. I assume it does, however when I use esttab (and estfe) it shows the fixed effects only for the second stage, so I am now confused. Also when it reports the regressions, the absorbed fixed effects appear only at the end.

Thank you in advance!

Paulo

**Comment by ArthurHowardMorris** [comment]
Paulo (and anyone else that googles their way here),

I can replicate what I think is your problem using `savefprefix` (a `ivreg2` option see `help ivreg2`) to save the first stage like this:

```Stata
clear all
sysuse auto
qui ivreghdfe price weight (length=gear), absorb(rep78) savefprefix(model1)
estimates store model1
estimates dir
estfe model1* , labels(rep78 "Rep 78 FE")
esttab model1* , indicate("First stage = c1" `r(indicate_fe)') // a solution based on c1 may also be possible
```

You'll notice that the first stage indicates "No" for the FE even though ivreghdfe absorbed them in both stages (I believe this is what Paulo is talking about).

The issue is that `savefprefix()` doesn't five the first stage the `e()` macros that `estfe` is looking for. You can verify this by looking at the source code for `estfe` and the saved estimates (look at `estimates dir` to see what the first stage is named, and `which estfe` to find the source code).

To solve this problem, simply restore the estimates you need to modify and add back the `e()` macros as follows:

```Stata
clear all
sysuse auto
qui ivreghdfe price weight (length=gear), absorb(rep78) savefprefix(model1)
// store the two missing e() macros
local absvars = e(extended_absvars)
local nabsvars = e(N_hdfe_extended)
estimates store model1
// restore the first stage and estadd the missing macros
estimates restore model1length
estadd local extended_absvars = "`absvars'"
estadd local N_hdfe_extended = "`nabsvars'"
estimates store model1length
// then apply estfe as usual 
estfe model1* , labels(rep78 "Rep 78 FE")
esttab model1* , indicate(`r(indicate_fe)')
```

**Comment by Aimeeli847** [comment]
> Paulo (and anyone else that googles their way here),
> 
> I can replicate what I think is your problem using `savefprefix` (a `ivreg2` option see `help ivreg2`) to save the first stage like this:
> 
> ```stata
> clear all
> sysuse auto
> qui ivreghdfe price weight (length=gear), absorb(rep78) savefprefix(model1)
> estimates store model1
> estimates dir
> estfe model1* , labels(rep78 "Rep 78 FE")
> esttab model1* , indicate("First stage = c1" `r(indicate_fe)') // a solution based on c1 may also be possible
> ```
> 
> You'll notice that the first stage indicates "No" for the FE even though ivreghdfe absorbed them in both stages (I believe this is what Paulo is talking about).
> 
> The issue is that `savefprefix()` doesn't five the first stage the `e()` macros that `estfe` is looking for. You can verify this by looking at the source code for `estfe` and the saved estimates (look at `estimates dir` to see what the first stage is named, and `which estfe` to find the source code).
> 
> To solve this problem, simply restore the estimates you need to modify and add back the `e()` macros as follows:
> 
> ```stata
> clear all
> sysuse auto
> qui ivreghdfe price weight (length=gear), absorb(rep78) savefprefix(model1)
> // store the two missing e() macros
> local absvars = e(extended_absvars)
> local nabsvars = e(N_hdfe_extended)
> estimates store model1
> // restore the first stage and estadd the missing macros
> estimates restore model1length
> estadd local extended_absvars = "`absvars'"
> estadd local N_hdfe_extended = "`nabsvars'"
> estimates store model1length
> // then apply estfe as usual 
> estfe model1* , labels(rep78 "Rep 78 FE")
> esttab model1* , indicate(`r(indicate_fe)')
> ```

HOW to outut the results table into excel or word???????
Thanks

**Comment by pfagandi** [comment]
> Paulo (and anyone else that googles their way here),
> 
> I can replicate what I think is your problem using `savefprefix` (a `ivreg2` option see `help ivreg2`) to save the first stage like this:
> 
> ```stata
> clear all
> sysuse auto
> qui ivreghdfe price weight (length=gear), absorb(rep78) savefprefix(model1)
> estimates store model1
> estimates dir
> estfe model1* , labels(rep78 "Rep 78 FE")
> esttab model1* , indicate("First stage = c1" `r(indicate_fe)') // a solution based on c1 may also be possible
> ```
> 
> You'll notice that the first stage indicates "No" for the FE even though ivreghdfe absorbed them in both stages (I believe this is what Paulo is talking about).
> 
> The issue is that `savefprefix()` doesn't five the first stage the `e()` macros that `estfe` is looking for. You can verify this by looking at the source code for `estfe` and the saved estimates (look at `estimates dir` to see what the first stage is named, and `which estfe` to find the source code).
> 
> To solve this problem, simply restore the estimates you need to modify and add back the `e()` macros as follows:
> 
> ```stata
> clear all
> sysuse auto
> qui ivreghdfe price weight (length=gear), absorb(rep78) savefprefix(model1)
> // store the two missing e() macros
> local absvars = e(extended_absvars)
> local nabsvars = e(N_hdfe_extended)
> estimates store model1
> // restore the first stage and estadd the missing macros
> estimates restore model1length
> estadd local extended_absvars = "`absvars'"
> estadd local N_hdfe_extended = "`nabsvars'"
> estimates store model1length
> // then apply estfe as usual 
> estfe model1* , labels(rep78 "Rep 78 FE")
> esttab model1* , indicate(`r(indicate_fe)')
> ```

Thank you, that is precisely what I was talking about in the question, so the issue was the macros, but the regression is ok. This can be esttout with esttab just adding the using as usual.

**Comment by sergiocorreia** [comment]
> Paulo (and anyone else that googles their way here),
> 
> I can replicate what I think is your problem using `savefprefix` (a `ivreg2` option see `help ivreg2`) to save the first stage like this:
> ```

Thanks for the detailed reply Arthur. As you discovered, `estfe` was not designed with ivreghdfe in mind (but can be easily adapted)
