### ISSUE TITLE
Development branch throws new error: "e(df_r) doesn't match"

### ISSUE THREAD

**Issue by NilsEnevoldsen** [sergiocorreia/reghdfe#5]
Load:

| x | i | j | y |
|---|---|---|---|
| 0 | 1 | 1 | 1 |
| 1 | 1 | 2 | 1 |
| 1 | 2 | 2 | 2 |
| 1 | 3 | 3 | 3 |
| 1 | 3 | 2 | 3 |

Run:
```stata
reghdfe y x, absorb(i j)
```

Stable branch result:
> WARNING! Missing FStat
> Note: equality df_m+1==rank failed (is there a collinear variable in the RHS?), running -test- to get correct values
> [Table omitted]

Development branch result:
> e(df_r) doesn't match: 3!=4

**Comment by sergiocorreia** [comment]
Hi Nils,

This is caused by what I believe is a subtle bug within Stata. I'll give an example with the -hdfe- command (available from this repo, as described in the readme.md)

```stata
* Create your dataset
input x y i j
0 1 1 1
1 1 1 2
1 2 2 2
1 3 3 3
1 3 3 2
end

* Apply within transformation
hdfe y x, a(i j) clear

* Regress; notice that both X and cons are dropped
reg y x

* However, Stata still counts X as not dropped when computing df_m!!!
di e(df_m)

* The reason is due to numerical accuracy:
* The part of regress that decides whether to drop or not uses more less accuracy
* Than the part of regress that computes e(df_m)
su x
* If you run the hdfe command with the tol(1e-10) option, you will see that now e(df_m)==0

* Also, in the case below e(df_m) IS zero (just to make sure that they do exclude dropped variables when computing df_m)
gen z = 0
reg y z
di e(df_m)
```

I'm not entirely sure about how to proceed. One option would be to override the e(df_m) from regress, thus fixing their bug manually.

**Comment by sergiocorreia** [comment]
By the way, I added the above solution to the latest build. Not the most "kosher" solution, but is probably the best for now.
