### ISSUE TITLE
feature request : fama-macbeth

### ISSUE THREAD

**Issue by randomgambit** [sergiocorreia/reghdfe#57]
Hi Sergio,

Thank you again for your great work

I am using `reghdfe `on a daily basis (I love to estimate highly-dimensional fixed effects linear models) and I would like to know if you would be able to implement a fama-macbeth procedure for reghdfe. For instance, you could add a `-fmb` option such that `reghdfe y x, fmb newey(4) ` estimates a fama macbeth regression with Newey standard errors.

Indeed:

-  it would be very useful to be able to use reghdfe to estimate fixed effects models, and then compare the estimates with a fama-macbeth regression without changing the syntax too much (and in particular, without changing the esttab code too much)
-  the existing stata packages for fama macbeth are super old and cumbersome (weird tsset requirements, factor syntax not working which is horrible for interactions, etc)

What do you think? 

I believe that should be very easy for you. Yet, that will increase the appeal of `reghdfe `ever further (consider all the asset pricing papers that use fama-macbeth as a complement to portfolio sorts)...

Thanks!

**Comment by sergiocorreia** [comment]
Hi Olaf,

That sounds really interesting, but as I am not doing much in terms of asset pricing lately, I'm afraid it would not be worth it for me to invest time in that (vs improving on other of the existing features). If I become aware of anyone that extends reghdfe to easily support FM, I'll let you know for sure (and if you are interested at some point, I can give you a few pointers).

Best,
S

**Comment by randomgambit** [comment]
Thanks Sergio,

Your point makes a lot of sense.

However, let me add a couple of arguments ;-)

- first, you want your program to have a user base as large as possible. Including fama-macbeth regression will definitely capture the asset-pricing crowd, and also anyone that needs to use this procedure
- given your econometric skills, implementing that is really simple. Recall that a fama macbeth is simply a cross sectional regression every day, and then you take the average of the coefficients over time. That's it!
- you already know how to program regressions in Stata, how to use factor syntax, etc.

All in all, very little input for a large potential gain in popularity. Isnt that what you want when you write a package? :)

**Comment by sergiocorreia** [comment]
It does look quite interesting and useful. That said, i) I'm a middle of a large rewrite so in any case it would need to wait until that is done, and ii) my work incentives are really towards producing more papers, so in general the rule I've followed is to add features when I need them (reghdfe is a byproduct of my JMP; adding multiway clustering happened when one of my advisors asked for such tables, etc.).

One of the objectives of the rewrite is to make the code simpler to modify and extend, so ideally in the future you could write a FM program that just calls reghdfe.

I'll close the issue but nonetheless I'll my eyes open for extending reghdfe to broader cases.

Cheers,
Sergio
