### ISSUE TITLE
Using if with condition on string variable

### ISSUE THREAD

**Issue by poliquin** [sergiocorreia/reghdfe#60]
`reghdfe` throws a 111 error when using `if` with a string variable:

``` stata
webuse nlswork
decode race, gen(raza)

// this runs fine
reghdfe ln_wage union hours if race == 1, absorb(id)

// this throws an error
reghdfe ln_wage union hours if raza == "white", absorb(id)
```

The last command results in:

```
white not found
r(111);
```

The expected behavior is to simply limit the sample on the string variable.

The above example may seem contrived, but limiting on a string variable has practical uses: e.g. a state-year dataset where the model excludes the District of Columbia: `if state != "DC"`. 

*! reghdfe 3.2.1 25jul2015

**Comment by sergiocorreia** [comment]
Does it also fail with the version in github?

**Comment by sergiocorreia** [comment]
Found the bug:

> local exp "= `weightvar'"

I need to change that to compound quotes to fix it..

In the meantime, for some reason this equivalent command seems to work:

```
reghdfe ln_wage union hours if inlist(raza,"white"), absorb(id)
```

**Comment by sergiocorreia** [comment]
Works in dev version; closed
