### ISSUE TITLE
Factor variables not allowed in absorb

### ISSUE THREAD

**Issue by Danferno** [sergiocorreia/reghdfe#64]
Currently, factor variables (e.g. L(0/4).var) are not allowed in the absorb section. It would be very convenient if this option was added.

**Comment by sergiocorreia** [comment]
This might be quite doable. Can you give me an example of when this could come in play? Usually factor variables do not change with time so I'm not sure what use cases are you thinking of

**Comment by Danferno** [comment]
In CCEP models mostly. The key-point of those estimator is that you include the cross-sectional means to the regression equation, interacted with your panel units. 

E.g.
xtset id t
reghdfe y x1 L(0/4).x2, absorb(id##c.(x1 L(0/4).x2) t)

I think using -tsrevar- might work here, though admittedly I have little experience with the command (and even less with what's going on behind the scenes in reghdfe, except that it's absolutely awesome).

**Comment by sergiocorreia** [comment]
Oh, that makes a lot of sense! (I was thinking about *absorb(L.id)*  which made less sense).

I'll add it as an option after updating the parse syntax.

Cheers,
S

**Comment by Danferno** [comment]
Thanks! And thanks for creating this command, I was literally stuck on my research because I couldn't get similar CCEP models to finish using xtreg (with N = 2000, you'd quickly move towards 10000 extra variables) whereas with reghdfe it seems to be no issue whatsoever :D

**Comment by sergiocorreia** [comment]
Great to hear that! I was in a similar situation while working on my PhD thesis so I know that feeling. Good luck with the projects! (and don't forget to cite the [paper](scorreia.com/research/hdfe.pdf) with the estimator :)

**Comment by sergiocorreia** [comment]
Fixed by https://github.com/sergiocorreia/moresyntax/commit/9a2ef4886887046498c370d36f632ee09601dada

Fix tested by 497fcc7693329cedd9dddc794c54944d4530d0b3
