### ISSUE TITLE
can we directly get individual cell means?

### ISSUE THREAD

**Issue by randomgambit** [sergiocorreia/reghdfe#67]
Hi Sergio,

I have a quick question for you if you have some time. I am using `reghdfe` to estimate a model such as

`y_it =i.A##i.B##i.C + day_fe + stock_fe`

where `A`, `B` and `C` are categorical variables. I would like reghdfe to show in the regression output the means for all possible cells (all possible combinations of A, B, C). That is, after controlling for day and stock fe, I can get the average y for all possible combinations of A,B,C.

regressing y on `ibn.A#ibn.B#ibn.C` does not work (reghdfe gives only one mean), contrary to example `1.3` here http://www.ats.ucla.edu/stat/stata/faq/no_main_effect.htm where Stata correcly returns the individual cell means.

Is the output above possible with reghdfe without having to `lincom` the coefficients myself?

Thanks!

**Comment by sergiocorreia** [comment]
(quick reply b/C I'm on mobile and will be for the next days)

Sadly there is no way with the current version. This is because of a conflict with the syntax command.

That said, I borrowed the fix that ivreg2 did so the next version should fix this and all the other factor bugs.

**Comment by randomgambit** [comment]
ok enjoy your vacation!

**Comment by sergiocorreia** [comment]
Fixed on the dev version:

```
use http://www.ats.ucla.edu/stat/data/hsbanova, clear
gen c = 1
reghdfe write i.female#i.grp , a(c) // this works ok
 reghdfe write i.female#i.grp , a(c) old // this excludes some interactions
 regress write i.female#i.grp // benchmark
```
