### ISSUE TITLE
reghdfe error message "option sdofminus() not allowed"

### ISSUE THREAD

**Issue by veronesse** [sergiocorreia/reghdfe#69]
Hello! I updated Stata 14 this morning and the reghdfe with IV doesn't work anymore for the following regression:

reghdfe easing (L_sp_for_pct=L_sp_for_adj_pct) [pw=L_sp_total],  vce(cluster id_c) absorb(id_c id_v)

The error message is "option sdofminus() not allowed". I don't know where the problem could come from. 

Thanks for helping,
Veronica

**Comment by sergiocorreia** [comment]
What version of -reghdfe- and -ivreg2- are you using? (type `ivreg2, version` and `reghdfe, version`) On my laptop, with reghdfe 3.2.7 and ivreg2 4.1.10 , the following works fine:

```stata
sysuse auto
reghdfe price (weight=gear) [pw=length], vce(cluster turn) absorb(turn trunk)
```

Best,
S

**Comment by veronesse** [comment]
Thank you! Indeed the issue was the version of the ado files.
