### ISSUE TITLE
if condition raises a type mismatch if variable is a string

### ISSUE THREAD

**Issue by palpen** [sergiocorreia/reghdfe#72]
Hello,

It looks like reghdfe fails whenever the if condition uses a string variable that is numeric:

```
sysuse auto, clear

// this works
gen heavy_car = "heavy"
replace heavy_car = "not_heavy" if weight < 2600
reghdfe price mpg if heavy_car == "heavy", absorb(foreign)

// this doesn't
gen heavy_car_ind = "1"
replace heavy_car_ind = "0" if weight < 2600
reghdfe price mpg if heavy_car_ind == "1", absorb(foreign)
```

For my application, I need the if condition variable to be the string version of the numeric value. This is because for some observations the variable contain leading zeroes (they are industrial classifications where "0123" is a different industry from "123").

Thanks!
Palermo

**Comment by sergiocorreia** [comment]
For some reason, spaces seem to make a difference:

```stata
// This works
reghdfe price mpg if heavy_car_ind=="1", absorb(foreign)
```

So as a short term solution you can do that. Long term, I need to fix a bug in Compact.ado and replace `if(string)` with `if(string asis)` to allow for quotes with spaces (and probably repeat that in other places)

Best,
S

**Comment by palpen** [comment]
Perfect! this is good for now. Thanks for your help.

**Comment by sergiocorreia** [comment]
Fixed in dev version
