### ISSUE TITLE
Using cache for alternative dependent variables.

### ISSUE THREAD

**Issue by stevecicala** [sergiocorreia/reghdfe#75]
I have a few outcomes all run with the same independent variables, but am having trouble using the cache to estimate coefficients for the new outcomes on the transformed independent variables. For example, supposing `gear_ratio` were a second outcome variable to be run against the example online:

`sysuse auto`
`reghdfe price weight length, absorb(turn rep) cache(save, keep(gear_ratio))`
`reghdfe gear_ratio weight length, a(turn rep) cache(use)`

I get: 
`couldn't find the match of gear_ratio in the cache (details: set=depvar; factors=gear_ratio)`

**Comment by sergiocorreia** [comment]
The first call is not really a regression but lists all the variables used, so it should be

```
sysuse auto
reghdfe price weight length gear_ratio, absorb(turn rep) cache(save)
reghdfe gear_ratio weight length, a(turn rep) cache(use)
```

Let me know if that works for you

(The keep suboption is for more advanced uses, like when wrapping reghdfe from another command; e.g. from `regife`)

**Comment by stevecicala** [comment]
Perfect, thanks!
