### ISSUE TITLE
inconsistency between t-value and p-value

### ISSUE THREAD

**Issue by slf99** [sergiocorreia/reghdfe#76]
I use the below code to conduct panel regression controling firm fixed effect and clustering firm and quarter:

reghdfe lead4 newsepu q cf saleg, absorb(gvkey ) vce(cluster quarter gvkey)

As the below results show, the t-statistics of salesg is 3.88, while P-statistics of saleg is 0.03. The t-stastistics is inconsistent with the p-value. It seems that the calculation of p-value is not based on t-statistics. Which statistics can I rely on?

The version of reghdfe is 3.2.9 21feb2016.

HDFE Linear regression	Number of obs   =    353,013
Absorbing 1 HDFE group	F(   4,      3) =      95.73
Statistics robust to heteroskedasticity	Prob > F        =     0.0017
	R-squared       =     0.4599
	Adj R-squared   =     0.4429
Number of clusters (quarter) =          4	Within R-sq.    =     0.0483
Number of clusters (gvkey)   =     10,805	Root MSE        =     0.0440

(Std. Err. adjusted	for 4 clusters in quarter gvkey)
	
Robust
   lead4           Coef.   Std. Err.           t	    P>t     [95% Conf. Interval]
	
newsepu    -.000054   .0000109    -4.95	0.016    -.0000886   -.0000193
q                .0022541   .0004591     4.91	0.016      .000793    .0037153
cf               .0975493    .014955     6.52	0.007     .0499557    .1451429
saleg         .0017417   .0004489     3.88	0.030     .0003131    .0031704

**Comment by sergiocorreia** [comment]
It seems you only have 3 degrees of freedom because you are onlhy clustering by quarter (and there are only 4 quarters in your sample). Did you use quarter as {1,2,3,4} or as actual year-quarter pairs?

If those are the correct DoF, then the pval does match the tstat:

```stata
. di tprob(3, 3.88)
.03032345

```

**Comment by slf99** [comment]
Thanks for your quick response.

If p-value is based on DoF of 3, then P-value is indeed 0.03032345. So, as you mentioned, the question is whether the DoF is correct.

Yes, I use quarter as {1,2,3,4}. But, I cluster on both firm and quarter level. Gvkey proxies the firm. When I only cluster on firm level, the DoF is 10,804. Based on your response, it seems that if I addtionally cluster by quarter, the additional clustering of quarter can decrease DoF from 10,804 into 3. Did I understand correctly?

Thanks,
Best Regards

**Comment by sergiocorreia** [comment]
Yes. the effective number of clusters when you have multi-way-clustering is `min(#1, #2) = min(10804, 4) = 4`. That's why it's extremely rare to cluster by quarter instead of by year quarter (e.g. 2016q1, 2016q2, etc.)

**Comment by slf99** [comment]
I see your point. Thanks very much.
