### ISSUE TITLE
Problems with build process

### ISSUE THREAD

**Issue by poliquin** [sergiocorreia/reghdfe#77]
I do not understand how the files in `package/` are actually built. I do the following...

1. Clean checkout of `master`
2. Everything appears to be working correctly.
3. Run `python build/build.py` (everything completes fine)
4. The files in `package` all change substantially and `reghdfe` no longer runs:
    > file assert_msg.mata not found
    > (error occurred while loading reghdfe.ado)
    > r(601);

I expected the build script to essentially re-produce the files in `package`, perhaps with nothing but a version change. The cause of the above error is the new `include` lines in `reghdfe.ado` (e.g. line 31 is now `include assert_msg.mata` whereas `master/reghdfe.ado` is `mata set matastrict on` and there are no `include xyz.mata` lines).

I must be missing a build step.

**Comment by sergiocorreia** [comment]
You are doing it correctly, but the current build in master is broken (next time I'll try to do experimental stuff on other branches).

If you go back 10 commits or so (to the June builds), those one should work.

Currently, my main problem is that the code is too complex and it's hard to add stuff. To solve this, I decoupled part of the internals into [ftools](https://github.com/sergiocorreia/ftools/) and the parsing part will be split into another project, so reghdfe should end up as a smaller streamlined package (as it was on prev. versions).

PS: Are you trying to fix a bug or working on a feature?

**Comment by poliquin** [comment]
Thanks for the notice, and the excellent project!
I was adding some code that would preserve variable labels when doing `cache(save)`.

**Comment by sergiocorreia** [comment]
You might want to do it through Mata, as in [this](https://github.com/sergiocorreia/ftools/blob/master/source/ftools.mata#L181) line

Basically:

```stata
clear all
sysuse auto, clear
mata: mata set matastrict off

mata:

transmorphic scalar preserve_varlist(string scalar varlist)
{
	vars = tokens(varlist)
	A = asarray_create()
	for (i=1; i<=cols(vars); i++) {
		asarray(A, vars[i], st_varlabel(vars[i]))
	}
	return(A)
}

void restore_varlist(string scalar varlist, transmorphic scalar A)
{
	vars = tokens(varlist)
	for (i=1; i<=cols(vars); i++) {
		st_varlabel(vars[i], asarray(A, vars[i]))
	}
}

end

// Here we store the var labels for price and weight
mata: backup = preserve_varlist("price weight")
describe price

// Modify one
la var price "Something else"
describe price

// And restore it
mata: restore_varlist("price weight", backup)
describe price
```

Cheers!
S

**Comment by sergiocorreia** [comment]
Closing this issue as the new version now longer requires a build step (at the cost of a few files instead of a single large file).
