### ISSUE TITLE
Inconsistent reporting of R2 with heterogeneous slopes

### ISSUE THREAD

**Issue by dgreeniel** [sergiocorreia/reghdfe#78]
I noticed that when absorbing interactions with slopes, the R2 reported by reghdfe depends on the order you put in the absorb variables. See the reproduction below

```
webuse nlswork, clear
reghdfe ln_w grade age ttl_exp tenure not_smsa south , absorb(occ idcode#c.year)
reghdfe ln_w grade age ttl_exp tenure not_smsa south , absorb(idcode#c.year occ)
```

The first reports an R^2 of 0.9778 and the second reports 0.7010. This pattern also appeared in my own dataset--any time the heterogenous slope is listed last the R^2 becomes very high.

I really enjoy your commands, thank you actively developing useful tools for Stata!

**Comment by sergiocorreia** [comment]
In general, having something like `idcode#c.year` in absvars is [slow](https://github.com/sergiocorreia/reghdfe/issues/40) and creates large numerical errors (which doesn't happen if you also include an intercept for every idcode, i.e. `idcode##c.year`)

This is mentioned briefly in the help file ("Slope-only absvars ("state#c.time") have poor numerical stability and slow convergence.  If you need those, either i) increase tolerance or ii) use slope-and-intercept absvars...").

However, what you are describing seems to be an extreme case of this problem, where the results are clearly misleading.

In a few experiments it seems that the error goes away if I add a constant absvar at the end (even if its redundant):

```stata
webuse nlswork, clear
gen byte c = 1
reghdfe ln_w grade age ttl_exp tenure not_smsa south , absorb(occ idcode#c.year)
reghdfe ln_w grade age ttl_exp tenure not_smsa south , absorb(occ idcode#c.year c)
```

I'll try to use this to pinpoint the bug, but if I can't find it shortly I'll probably disable cont. interactions to prevent others hitting the bug. Let me know if you find other cases where it triggers.

Best,
S
