### ISSUE TITLE
Report AIC / support "estat ic"

### ISSUE THREAD

**Issue by Danferno** [sergiocorreia/reghdfe#79]
Hey!

One potentially useful addition would be to support AIC calculation, either in the ereturn list or by supporting "estat ic". I believe the formula is AIC = -2*e(ll) + 2*e(df_r).

Cheers
Jesse

**Comment by sergiocorreia** [comment]
Makes sense. BTW, is AIC still encouraged by the stats/metrics literature, or are they switching more to BIC and so on?

**Comment by Danferno** [comment]
To be entirely honest, I have no idea. I know a guy who's specialised in this stuff though, so I'll ask him.

**Comment by sergiocorreia** [comment]
Implemented in 9713eb0f0f2935efb15de55481b4a5ee80a9867e (on the dev branch)

It replicates the behavior of areg and xtreg, but let me know if there is anything better
