### ISSUE TITLE
Minor bug: Error message when not all FE saved

### ISSUE THREAD

**Issue by Danferno** [sergiocorreia/reghdfe#89]
> reghdfe ln_W_rest  L1_ln_W_rest L2_ln_W_rest  L0_ln_MW L1_ln_MW L2_ln_MW ln_pop ln_W_tot, cluster(state) absorb(quarter)
> . reghdfe $depvar ${Lx_$depvar} ${Lx_$indepvar} $controls, cluster($clustervar) absorb($timevar)
> (converged in 1 iterations)
> 
> <output suppressed>
> . predict res_`name', r
> In order to predict, all the FEs need to be saved with the absorb option (# was not)
> For instance, instead of absorb(i.year i.firm), set absorb(FE_YEAR=i.year FE_FIRM=i.firm)

I assume the **#** is supposed to be a number? Very minor issue of course.

PS: I'm aware of using the residuals() option, this was just sloppy coding on my part

**Comment by sergiocorreia** [comment]
What version of Stata are you using? Also what is the output of "reghdfe,version"?

**Comment by Danferno** [comment]
Stata 14.2

. reghdfe, version
3.2.9 21feb2016

Dependencies installed?
- ivreg2            yes
- avar              not
- tuples            yes

**Comment by sergiocorreia** [comment]
Can you try with the latest release from Github (4.1.x)?

https://github.com/sergiocorreia/reghdfe#install

**Comment by Danferno** [comment]
```
reghdfe $depvar ${Lx_$depvar} ${Lx_$indepvar} $controls, cluster($clustervar) absorb($timevar) residuals(res)
predict res, r
```

leads to 

> you must add the resid option to reghdfe before running this prediction

However, if I run the command with the residuals option, it does seem to be estimate the residuals.

`reghdfe $depvar ${Lx_$depvar} ${Lx_$indepvar} $controls, cluster($clustervar) absorb($timevar b=$panelvar) residuals(res2)`

Even if I only give name to one set of abs-vars.

**Comment by sergiocorreia** [comment]
Using the latest version (4.1.3 06apr), I can run the first command fine:

```stata
sysuse auto
reghdfe price weight, cluster(turn) absorb(trunk) residuals(res)
```

That said, I cannot run predict with a new variable called `res` because it is the same as the one I just generated with `residuals()`:

```stata
. predict res, r
variable res already defined
```

(Of course, there is no need to run predict to get the residuals if you already have them)

So, all in all I think you shouldn't even need to name the absvars with the new version (feel free to open the issue if that's not the case).

Best,
Sergio
