### ISSUE TITLE
Predicted values do not match xtreg (and appear wrong)

### ISSUE THREAD

**Issue by kyrenia** [sergiocorreia/reghdfe#90]
I ran a regression with xtreg and reghdfe, and followed both commands with predict to generate predicted values.

While the regression coefficients and standard errors with xtreg and reghdfe are exactly the same, the predicted values are very very different, and the numbers from reghdfe  are widely different from what i woudl expect them to be.

Specifically, my DV is centered at 1, so i would expect predicted values centered around that number. xtreg's produced predicted values that are in-line with what i would expect (i.e. has a mean of 1, to match my DV). reghdfe's predicted values are completely differently, and are all approximately 10% of the values from xtreg, -- and not a single predicted value is reasonable (i.e. i the max predicated value is about 0.4, whereas essentially none of my DV values are that low). 

[for reference - this was version 3.2.9 21feb2016 - maybe it has now been fixed]

**Comment by sergiocorreia** [comment]
Which prediction are you doing? xb or xbd?

**Comment by kyrenia** [comment]
Hi - I did:
 predict test
(option xb assumed; fitted values)

**Comment by sergiocorreia** [comment]
I wouldn't be surprised if the difference is due to the constant, which in reghdfe is part of the absorbed fixed effects and not of the regressors showed on the table.

Can you try running with xbd? Or computing the constant by hand and adding it, as discussed here: http://scorreia.com/software/reghdfe/faq.html#where-is-the-constant

**Comment by kyrenia** [comment]
The constant calculated manually comes out essentially the same as that calculated via xtreg. When i add that to the predicted numbers from reghdfe with the xb option, i get similar-ish predicted values to those from stata (within 10%) [they are certaintly plausible values - the distribution of the predicted values, now matches the DV]. The numbers from adding the xbd options are also more consistent (again within 10%), and are again plausible, although do not match up exactly. [that may be because reghdfe is dropping singular observations, of which i have a few ]

One thing though - the difference between the predicated values from reghdfe with "xb" and "xbd" does not seem to the constant- i.e., it is about the same as the constant, but does not equal it exactly. (for me, i have a constant of 0.8, but the difference between the predicted values with "xb" and "xbd" varies between 0.7 and 0.9]

**Comment by sergiocorreia** [comment]
You should be able to get the same results.

Using the keepsingletons option can help , as well as predicting with double precision for xtreg (I.e. "Predict double xb, xb"

**Comment by sergiocorreia** [comment]
About your last point: xbd is the constant and the fixed effect, so for sure it should not be the same as in adding just the constant. You can check the hel file for xtreg postestimation to see what xtreg is doing, to see which one you need to use to get the same results (don't remember it at the top of my head)
