### ISSUE TITLE
Error when using the cluster option

### ISSUE THREAD

**Issue by zhangyifei85** [sergiocorreia/reghdfe#92]
Sorry for not providing a replicable example.

When implementing the reghdfe stable release, I used the cluster option and got:
               * = fixed effect nested within cluster; treated as redundant for DoF computation

The exact same implementation gave out errors under the development version of the Reghdfe:
               st_data():  3204  matrix found where scalar required
          __fload_data():     -  function returned error
FixedEffects::estimate_dof():     -  function returned error
                 <istmt>:     -  function returned error

When I drop the cluster option, then the above error disappeared.

Of course, when I add the old option with the cluster (i.e. old version), everything is fine.

I am just wondering whether the error is just a bug in the development version or the stable version was wrong and you corrected it in the development version. By the way, the cluster error just arose today with the latest upgrading. I installed this development version in around 1-2 weeks ago and did not experience the similar problem.

Thanks a lot for building up this wonderful package.

**Comment by sergiocorreia** [comment]
What version are you using? (type `reghdfe, version`)

**Comment by zhangyifei85** [comment]
Thank you.  

The version is:
 *! version 4.1.3 06apr2017
Required packages installed?
- ftools            yes

It magically works fine now after I uninstalled the package and re-installed them again. I have no clue why it is the case. It is pretty fine now.

You might safely close this issue. Sorry for the bothering.

**Comment by sergiocorreia** [comment]
Might have been related with the recent changes in the ftools package; good to know it works now

**Comment by zhangyifei85** [comment]
Thanks again.
