### ISSUE TITLE
Savefe: How to obtain standard errors for estimated fixed effects?

### ISSUE THREAD

**Issue by photopresentr** [sergiocorreia/reghdfe#97]
Hi Sergio,

Many thanks for the reghdfe, it's a great tool!

I'm using the reghdfe for a gravity model with several sets of fixed effects. Savefe option stores the estimated coefficients of the fixed effects in separate variables. Is there a way to store the standard errors computed when estimating the fixed effects coefficients.

Stata version: 14.0

Thanks in advance

**Comment by sergiocorreia** [comment]
Sadly no, as we don't have a variance-covar matrix for those. You could use R'sfe package, which afaik does bootstrap.

Or I guess  you could do the bootstrap on your own with a loop. If you go that route, be sure to 1) follow lfe's approach , so you bootstrap at the correct unit, and 2) use the GitHub version of reghdfe which is way faster.

**Comment by photopresentr** [comment]
Dear Sergio,

thanks for the reply! We'll try to follow your recommendation
