### ISSUE TITLE
Instrumenting with version 4.x

### ISSUE THREAD

**Issue by RichMurphy** [sergiocorreia/reghdfe#99]
Hi, 
With the new version (4.3.0) I now get errors when trying to instrument an endogenous variable. 
sysuse auto.dta
reghdfe price weight (length=head), absorb(rep78)
assert(): 3498 assertion is false
<istmt>: - function returned error

I then re-installed today and got a different error from the same command 
fixed_effects(): 3499 precompute_inv_xx() not found 
<ismt>: - function  returned error

I've gone back to version 3.2.9 and it works.
If you need more details please get in touch. 
Cheers
Rich

**Comment by sergiocorreia** [comment]
See the second gotcha here: https://github.com/sergiocorreia/reghdfe/blob/master/Readme.md#things-to-be-aware-of

Using the modified ivreg2 should work, let me know if it doesn't

**Comment by leetucker** [comment]
Hi Sergio,

I am also receiving the "assertion is false" error, both on my own dataset and when using the auto dataset.  I reinstalled the ivreg2hdfe library, and I have been able to replicate the error on both a Linux and Windows version of Stata 14.  As with Rich, I can run the estimation using the "old" command with no issues, and the error only arises with IV regressions.

I am using reghdfe version 4.3.0 and ivreg2 version 04.1.10.  Let me know if you have any additional questions.

Thanks,
Lee Tucker

**Comment by leetucker** [comment]
From running the command with trace on, it looks like the error is popping up in reghdfe.ado, line 378:

`  - mata: hdfe_variables = HDFE.partial_out(HDFE.varlist, 1)
(MWFE estimator converged in 1 iterations)
  - if (`timeit') timer off 23
  = if (0) timer off 23
  - mata: assert(HDFE.model=="ols")
                assert():  3498  assertion is false
                 <istmt>:     -  function returned error
`

**Comment by sergiocorreia** [comment]
It's likely related to one of the recent updates in reghdfe. I'll try tackling it later tonight or tomorrow.

**Comment by sergiocorreia** [comment]
Hi Lee,

I think I know what's the problem. You can no longer run IVs with `reghdfe`, you need to use the other package for that. It was called `ivreg2hdfe` until a minute ago, but I just renamed it to `ivreghdfe` because there was another package with the same name.

You can see the install instructions here: https://github.com/sergiocorreia/ivreg2_demo

**Comment by RichMurphy** [comment]
Thanks that's great. 
Works a charm.
